;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        backward-delete-word
        backward-sexp
        comint-delchar-or-maybe-eof
        comment-dwim-or-line
        counsel-M-x
        counsel-yank-pop
        dabbrev-expand
        drag-stuff-down
        eval-and-replace
        forward-sexp
        indent-for-tab-command
        indent-rigidly
        ivy-done
        kill-region
        kmacro-end-and-call-macro
        mark-sexp
        org-beginning-of-line
        org-delete-char
        org-edit-special
        org-end-of-line
        org-kill-line
        org-open-line
        org-return
        org-self-insert-command
        org-yank
        py-electric-colon
        py-hungry-delete-backwards
        py-indent-or-complete
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        beginning-of-buffer
        counsel-find-file
        describe-key
        elpy-shell-send-statement-and-step
        end-of-buffer
        ivy-switch-buffer
        mark-whole-buffer
        move-windows
        org-export-dispatch
        projectile-rails-find-stylesheet
        swiper
        text-scale-decrease
        ))
