* things to research/do

look up (py) documentation:
https://stackoverflow.com/questions/45992859/how-to-read-python-documentation-in-emacs
- code nav: helm
- save window configs/workspaces: eyebrowse
- counsel-imenu
- treemacs with M-p M-n recent file traversal
- autocomplete fixen (company?)
- initialisms for filtering (selectrum?)
- save command line history thru sessions, and separate it per type of shell
  (python, zsh, etc)
- bookmarks? https://www.emacswiki.org/emacs/VisibleBookmarks
- copy code unindented
  https://emacs.stackexchange.com/questions/34966/copy-region-without-leading-indentation
- 'occur-selection' > find pattern (current selection) in projectile dir

* interesting configs?

- https://github.com/gonsie/dotfiles/blob/master/emacs

* keybindings that are still freeish

- C-c b
- C-x C-n (goal-column)

* basic emacs
** no debug

#+BEGIN_SRC emacs-lisp
(setq debug-on-error nil)
#+END_SRC

** startup

suppress noise on start up

#+BEGIN_SRC emacs-lisp
(setq-default inhibit-startup-screen t
              inhibit-splash-screen t
              initial-scratch-message "")
#+END_SRC

fullscreen

#+BEGIN_SRC emacs-lisp
(toggle-frame-fullscreen)
#+END_SRC

** put custom-set variables in =custom.el=, not =init.el=
#+BEGIN_SRC emacs-lisp
;; File for custom-set variables
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))
#+END_SRC

#+RESULTS:
: t
** random
fix mac meta keys

#+BEGIN_SRC emacs-lisp
(setq mac-option-key-is-meta nil
      mac-command-key-is-meta t
      mac-command-modifier 'meta
      mac-option-modifier 'super)
#+END_SRC

#+RESULTS:
: super

disable that big old yellow triangle in the center of the screen:

#+BEGIN_SRC emacs-lisp
(setq visible-bell t)
#+END_SRC

#+RESULTS:
: t

typing =C-n= on last line will create a newline:

#+BEGIN_SRC emacs-lisp
(setq next-line-add-newlines t)
#+END_SRC

#+RESULTS:
: t

be able to dynamically create functions:

#+BEGIN_SRC emacs-lisp
(defun define-named-lambda (name lambd args)
  (defalias (intern name) `(lambda () (interactive) (apply ,lambd ',args))))

(defun define-custom-function (name func)
  (define-named-lambda name (lambda () (funcall func))))
#+END_SRC

#+RESULTS:
: define-custom-function

** set/pop marks for navigation

apparently, transient-mark-mode is AWESOME but it can ruin the alternative use
of marks a little bit: saving positions quickly. so we bind keys for that.

from https://www.masteringemacs.org/article/fixing-mark-commands-transient-mark-mode

#+BEGIN_SRC emacs-lisp
(defun push-mark-no-activate ()
  "Pushes `point' to `mark-ring' and does not activate the region
   Equivalent to \\[set-mark-command] when \\[transient-mark-mode] is disabled"
  (interactive)
  (push-mark (point) t nil)
  (message "Pushed mark to ring"))

(global-set-key (kbd "C-`") 'push-mark-no-activate)

(defun jump-to-mark ()
  "Jumps to the local mark, respecting the `mark-ring' order.
  This is the same as using \\[set-mark-command] with the prefix argument."
  (interactive)
  (set-mark-command 1))
(global-set-key (kbd "M-`") 'jump-to-mark)

;; (defun exchange-point-and-mark-no-activate ()
;;   "Identical to \\[exchange-point-and-mark] but will not activate the region."
;;   (interactive)
;;   (exchange-point-and-mark)
;;   (deactivate-mark nil))
;; (define-key global-map [remap exchange-point-and-mark] 'exchange-point-and-mark-no-activate)
#+END_SRC

#+RESULTS:
: exchange-point-and-mark-no-activate

** unfill paragraph/region
#+BEGIN_SRC emacs-lisp
(defun unfill-paragraph ()
  (interactive)
  (let ((fill-column (point-max)))
    (fill-paragraph nil)))

(defun unfill-region ()
  (interactive)
  (let ((fill-column (point-max)))
    (fill-region (region-beginning) (region-end) nil)))

(global-set-key "\C-ceu" 'unfill-paragraph)
#+END_SRC

#+RESULTS:
: unfill-region

** kill-word

=M-backspace= not only deletes the previous word, but also copies it, which I
think is pretty annoying. Let's change this behaviour. The function called when
hitting =M-backspace= is =backward-kill-word=.

This is defined in simple.el, and it calls =kill-word=. Let's define a function
called delete-word, which

#+BEGIN_SRC emacs-lisp
(defun delete-word (arg)
  "Delete characters forward until encountering the end of a word.
With argument ARG, do this that many times."
  (interactive "p")
  (delete-region (point) (progn (forward-word arg) (point))))

(defun backward-delete-word (arg)
  "Delete characters backward until encountering the beginning of a word.
With argument ARG, do this that many times."
  (interactive "p")
  (delete-word (- arg)))

(global-set-key (kbd "M-<backspace>") `backward-delete-word)
#+END_SRC

#+RESULTS:
: backward-delete-word

#+BEGIN_SRC emacs-lisp
(defun kill-word (arg)
  "Kill characters forward until encountering the end of a word.
With argument ARG, do this that many times."
  (interactive "p")
  (delete-region (point) (progn (forward-word arg) (point))))
#+END_SRC

#+RESULTS:
: kill-word

** [paul] removing brackets around region

Taken from https://emacs.stackexchange.com/questions/10786/remove-parentheses-around-region

#+BEGIN_SRC emacs-lisp
(defun my-delete-surrounded-delimiters ()
  (interactive)
  ;; save where region begins & ends
  (let ((beginning (region-beginning))
        (end (region-end)))
        (save-excursion
        (goto-char end)
        (delete-char -1)
        (goto-char beginning)
        (delete-char 1))))

(defun my-move-region-inwards ()
  (interactive)
  ;; save where region begins & ends
  (let ((beginning (region-beginning))
        (end (region-end)))
    (save-excursion
      (goto-char (+ beginning 1))
      (set-mark)
      (goto-char (- end 1))
      (goto-char (+ beginning 1))
          ;; (delete-char -1)

          ;; (goto-char beginning)
          ;; (delete-char 1)
          )))

(global-set-key (kbd "C-M-<backspace>") `my-delete-surrounded-delimiters)
(global-set-key (kbd "C-M-r") `my-move-region-inwards)
#+END_SRC

#+RESULTS:
: my-move-region-inwards
* vital functions/libraries
** [paul] regexp-orrify

#+BEGIN_SRC emacs-lisp
(defun regexp-orrify (&rest disjuncts)
  "Return the regexp disjunction of the given regexps"
  (cond ((null disjuncts) "")
        ((null (cdr disjuncts)) (car disjuncts))
        (t (concat (car disjuncts)
                   "\\|"
                   (apply #'regexp-orrify (cdr disjuncts))))))
#+END_SRC

** s (string manipulation)

#+BEGIN_SRC emacs-lisp
(require 's)
#+END_SRC

#+RESULTS:
: s

* appearance
** font lock
#+BEGIN_SRC emacs-lisp
  ;; Enable pretty syntax highlighting everywhere
  (global-font-lock-mode t)
#+END_SRC

** Whitespace
#+BEGIN_SRC emacs-lisp
(use-package whitespace
  :ensure t
  :init (setq-default indicate-empty-lines t)
  :config
  (setq whitespace-line-column 80
        whitespace-style '(face trailing lines-tail empty
                                indentation::space space-before-tab::tab))
  (global-whitespace-mode -1))

(setq-default indent-tabs-mode nil)

(defcustom do-whitespace-cleanup t
  "Perform whitespace-cleanup on save."
  :group 'whitespace)

(make-variable-buffer-local 'do-whitespace-cleanup)

(defun toggle-whitespace-cleanup ()
  "Turn the whitespace-cleanup hook on and off."
  (interactive)
  (setq do-whitespace-cleanup (not do-whitespace-cleanup))
  (message "do-whitespace-cleanup set to %s" do-whitespace-cleanup))

(add-hook 'before-save-hook
          (lambda ()
            (when do-whitespace-cleanup
              (whitespace-cleanup))))

(add-hook 'makefile-mode-hook
          (lambda ()
            (setq indent-tabs-mode t
                  do-whitespace-cleanup nil)))

(add-hook 'prog-mode-hook
          (lambda ()
            (whitespace-mode +1)
            ;; (setq show-trailing-whitespace t)
            ))
#+END_SRC

#+RESULTS:
| lambda | nil | (whitespace-mode 1) |

** font
- [[https://www.emacswiki.org/emacs/SetFonts][Setting fonts]]
- See also ~/tmp/prettify-utils.el

** Decorations
Turn off all windows decoration.
#+BEGIN_SRC emacs-lisp
(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-all-mode 0)
(scroll-bar-mode 0)
(tooltip-mode )

#+END_SRC

#+RESULTS:
: t

** prettify
#+BEGIN_SRC emacs-lisp
(load-org "prettify.org")
#+END_SRC

#+RESULTS:
: Loaded ~/.emacs.d/prettify.el

** theming

themes i like:
| doom-laserwave |
| doom-palenight |
| doom-moonlight |

** doom-palenight

#+BEGIN_SRC emacs-lisp
;;; doom-palenight-theme.el --- inspired by Material-PaleNight -*- no-byte-compile: t; -*-
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
(use-package doom-themes
  :ensure t
  :config (load-theme 'doom-palenight t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)

  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))
#+END_SRC

#+RESULTS:
: t


#+BEGIN_SRC emacs-lisp
(defun light ()
  (interactive)
  (load-theme 'doom-opera-light t))

(defun dark ()
  (interactive)
  (load-theme 'doom-palenight t))

(dark)
#+END_SRC

#+RESULTS:
: doom-palenight-theme

** additional theming

change active region highlighting

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'region nil :background (doom-darken "#c792ea" 0.6) :foreground nil) ;; "#ffffff")
#+END_SRC

#+RESULTS:

disable/enable horizontal line where point is

#+BEGIN_SRC emacs-lisp
(global-hl-line-mode 0)
(set-face-background 'hl-line (doom-darken "#c792ea" 0.77))
#+END_SRC

#+RESULTS:

#+BEGIN_SRC emacs-lisp
;; (add-to-list 'load-path "~/.emacs.d/repos/elegant-emacs")
;; (require 'sanity)
;; ;; (require 'elegance)

(set-face-font 'default "Roboto Mono 12")

;; ;; (set-frame-parameter (selected-frame)
;; ;;                      'internal-border-width 24)
(setq default-frame-alist
      (append (list '(vertical-scroll-bars . nil)
                    ;; '(internal-border-width . 24)
                    '(font . "Roboto Mono 12"))))


;; ;; Line spacing, can be 0 for code and 1 or 2 for text
;; (setq-default line-spacing 0)

;; ;; Underline line at descent position, not baseline position
;; (setq x-underline-at-descent-line t)

;; ;; No ugly button for checkboxes
;; (setq widget-image-enable nil)

;; ;; No sound
;; (setq visible-bell t)
;; (setq ring-bell-function 'ignore)

;; ;; Paren mode is part of the theme
;; (show-paren-mode t)

;; ;; this is a purposefully long line that I hope will show some things in the fringe
;; ;; (fringe-mode '(10 . 10))
;; (defface fallback '((t :family "Fira Code Light"
;;                        :inherit 'face-faded)) "Fallback")
;; (set-display-table-slot standard-display-table 'truncation
;;                         (make-glyph-code ?… 'fallback))
;; (set-display-table-slot standard-display-table 'wrap
;;                         (make-glyph-code ?↩ 'fallback))

;; ;; Vertical window divider
;; (setq window-divider-default-right-width 3)
;; (setq window-divider-default-places 'right-only)
;; (window-divider-mode)
#+END_SRC

#+RESULTS:
: ((vertical-scroll-bars) (font . Roboto Mono 12))

* visual things
** matching parenthesis
#+BEGIN_SRC emacs-lisp
(show-paren-mode t)
(setq-default show-paren-style 'parenthesis) ; highlight brackets only

(defadvice show-paren-function
    (after show-matching-paren-offscreen activate)
  "If the matching paren is offscreen, show the matching line in
the echo area. Has no effect if the character before point is not
of the syntax class ')'."
  (interactive)
  (let* ((cb (char-before (point)))
   (matching-text (and cb
           (char-equal (char-syntax cb) ?\) )
           (blink-matching-open))))
    (when matching-text (message matching-text))))
#+END_SRC

#+RESULTS:
: show-paren-function
* prot
https://gitlab.com/protesilaos/dotfiles

add his prot-.el files to load-path:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/repos/protesilaos/dotfiles/emacs/.emacs.d/straight/repos/prot-lisp/")
#+END_SRC

#+RESULTS:
| ~/.emacs.d/repos/protesilaos/dotfiles/emacs/.emacs.d/straight/repos/prot-lisp/ | /home/paul/org-mode/lisp | ~/.emacs.d/elpa/use-package | /Users/jeroen/.emacs.d/elpa/ac-ispell-20151101.226 | /Users/jeroen/.emacs.d/elpa/ace-window-20200606.1259 | /Users/jeroen/.emacs.d/elpa/add-node-modules-path-20180710.2342 | /Users/jeroen/.emacs.d/elpa/adoc-mode-0.6.6 | /Users/jeroen/.emacs.d/elpa/afternoon-theme-20140104.1859 | /Users/jeroen/.emacs.d/elpa/auctex-12.2.3/ | /Users/jeroen/.emacs.d/elpa/auctex-12.2.3 | /Users/jeroen/.emacs.d/elpa/avy-20200624.1148 | /Users/jeroen/.emacs.d/elpa/beacon-1.3.4 | /Users/jeroen/.emacs.d/elpa/blacken-20200626.2018 | /Users/jeroen/.emacs.d/elpa/counsel-20200615.1226 | /Users/jeroen/.emacs.d/elpa/cyberpunk-theme-20200601.1632 | /Users/jeroen/.emacs.d/elpa/dashboard-20201215.1310 | /Users/jeroen/.emacs.d/elpa/doom-themes-20201107.315 | /Users/jeroen/.emacs.d/elpa/emmet-mode-20180613.341 | /Users/jeroen/.emacs.d/elpa/expand-region-20200304.1839 | /Users/jeroen/.emacs.d/elpa/flymake-eslint-20191129.1558 | /Users/jeroen/.emacs.d/elpa/helm-3.6.2 | /Users/jeroen/.emacs.d/elpa/helm-core-3.6.2 | /Users/jeroen/.emacs.d/elpa/htmlize-20200816.746 | /Users/jeroen/.emacs.d/elpa/hydra-20200711.1210 | /Users/jeroen/.emacs.d/elpa/jedi-20191011.1750 | /Users/jeroen/.emacs.d/elpa/auto-complete-1.5.1 | /Users/jeroen/.emacs.d/elpa/jedi-core-0.2.8 | /Users/jeroen/.emacs.d/elpa/epc-0.1.1 | /Users/jeroen/.emacs.d/elpa/ctable-0.1.2 | /Users/jeroen/.emacs.d/elpa/concurrent-0.5.1 | /Users/jeroen/.emacs.d/elpa/js-format-20170119.102 | /Users/jeroen/.emacs.d/elpa/js2-mode-20200725.112 | /Users/jeroen/.emacs.d/elpa/latex-unicode-math-mode-0.3.1 | /Users/jeroen/.emacs.d/elpa/lv-20200507.1518 | /Users/jeroen/.emacs.d/elpa/magit-2.90.1 | /Users/jeroen/.emacs.d/elpa/git-commit-2.90.1 | /Users/jeroen/.emacs.d/elpa/ghub-3.3.0 | /Users/jeroen/.emacs.d/elpa/magit-popup-2.13.2 | /Users/jeroen/.emacs.d/elpa/markdown-mode-2.4 | /Users/jeroen/.emacs.d/elpa/markup-faces-1.0.0 | /Users/jeroen/.emacs.d/elpa/multiple-cursors-1.4.0 | /Users/jeroen/.emacs.d/elpa/nginx-mode-1.1.9 | /Users/jeroen/.emacs.d/elpa/ob-ipython-20180224.953 | /Users/jeroen/.emacs.d/elpa/dash-functional-20200617.702 | /Users/jeroen/.emacs.d/elpa/olivetti-20201029.922 | /Users/jeroen/.emacs.d/elpa/org-20201109 | /Users/jeroen/.emacs.d/elpa/org-bullets-20200317.1740 | /Users/jeroen/.emacs.d/elpa/org-journal-2.0.0 | /Users/jeroen/.emacs.d/elpa/page-break-lines-20200305.244 | /Users/jeroen/.emacs.d/elpa/pdf-tools-20200512.1524 | /Users/jeroen/.emacs.d/elpa/pinentry-0.1 | /Users/jeroen/.emacs.d/elpa/pkgbuild-mode-0.14 | /Users/jeroen/.emacs.d/elpa/poporg-20170403.751 | /Users/jeroen/.emacs.d/elpa/popup-0.5.8 | /Users/jeroen/.emacs.d/elpa/prettier-js-20180109.726 | /Users/jeroen/.emacs.d/elpa/projectile-rails-20200916.1458 | /Users/jeroen/.emacs.d/elpa/inf-ruby-20200826.1458 | /Users/jeroen/.emacs.d/elpa/inflections-20170913.916 | /Users/jeroen/.emacs.d/elpa/projectile-20200916.814 | /Users/jeroen/.emacs.d/elpa/pygen-20161121.506 | /Users/jeroen/.emacs.d/elpa/elpy-1.34.0 | /Users/jeroen/.emacs.d/elpa/highlight-indentation-0.7.0 | /Users/jeroen/.emacs.d/elpa/company-0.9.12 | /Users/jeroen/.emacs.d/elpa/python-environment-0.0.2 | /Users/jeroen/.emacs.d/elpa/deferred-0.5.1 | /Users/jeroen/.emacs.d/elpa/python-mode-20200608.737 | /Users/jeroen/.emacs.d/elpa/pyvenv-1.21 | /Users/jeroen/.emacs.d/elpa/rainbow-delimiters-20200827.321 | /Users/jeroen/.emacs.d/elpa/rainbow-mode-1.0.4 | /Users/jeroen/.emacs.d/elpa/rake-20180212.1008 | /Users/jeroen/.emacs.d/elpa/f-20191110.1357 | /Users/jeroen/.emacs.d/elpa/request-20200517.1305 | /Users/jeroen/.emacs.d/elpa/scss-mode-0.5.0 | /Users/jeroen/.emacs.d/elpa/solarized-theme-20200717.1054 | /Users/jeroen/.emacs.d/elpa/sublime-themes-20170606.1844 | /Users/jeroen/.emacs.d/elpa/swiper-20200503.1102 | /Users/jeroen/.emacs.d/elpa/ivy-20200615.1103 | /Users/jeroen/.emacs.d/elpa/tablist-1.0 | /Users/jeroen/.emacs.d/elpa/tide-20200823.524 | /Users/jeroen/.emacs.d/elpa/flycheck-20200820.1403 | /Users/jeroen/.emacs.d/elpa/pkg-info-20150517.1143 | /Users/jeroen/.emacs.d/elpa/epl-20180205.2049 | /Users/jeroen/.emacs.d/elpa/toml-mode-20161107.1800 | /Users/jeroen/.emacs.d/elpa/treepy-0.1.1 | /Users/jeroen/.emacs.d/elpa/typescript-mode-20200817.817 | /Users/jeroen/.emacs.d/elpa/unicode-fonts-0.4.10 | /Users/jeroen/.emacs.d/elpa/ucs-utils-0.8.4 | /Users/jeroen/.emacs.d/elpa/font-utils-0.7.8 | /Users/jeroen/.emacs.d/elpa/persistent-soft-0.8.10 | /Users/jeroen/.emacs.d/elpa/list-utils-0.4.6 | /Users/jeroen/.emacs.d/elpa/pcache-0.4.2 | /Users/jeroen/.emacs.d/elpa/use-package-2.4 | /Users/jeroen/.emacs.d/elpa/bind-key-2.4 | /Users/jeroen/.emacs.d/elpa/virtualenvwrapper-0.2.0 | /Users/jeroen/.emacs.d/elpa/s-1.12.0 | /Users/jeroen/.emacs.d/elpa/visual-fill-column-1.11 | /Users/jeroen/.emacs.d/elpa/vlf-1.7.1 | /Users/jeroen/.emacs.d/elpa/web-mode-20200826.1954 | /Users/jeroen/.emacs.d/elpa/which-key-20200908.2301 | /Users/jeroen/.emacs.d/elpa/with-editor-2.9.3 | /Users/jeroen/.emacs.d/elpa/async-1.9.4 | /Users/jeroen/.emacs.d/elpa/wrap-region-20140117.720 | /Users/jeroen/.emacs.d/elpa/dash-2.17.0 | /Users/jeroen/.emacs.d/elpa/yaml-mode-20200518.914 | /Users/jeroen/.emacs.d/elpa/yasnippet-20200604.246 | /Users/jeroen/.emacs.d/elpa/zones-2019.7.13 | /Library/Application Support/Emacs/27.1/site-lisp | /Library/Application Support/Emacs/site-lisp | /Applications/Emacs.app/Contents/Resources/site-lisp | /Applications/Emacs.app/Contents/Resources/lisp | /Applications/Emacs.app/Contents/Resources/lisp/vc | /Applications/Emacs.app/Contents/Resources/lisp/url | /Applications/Emacs.app/Contents/Resources/lisp/textmodes | /Applications/Emacs.app/Contents/Resources/lisp/progmodes | /Applications/Emacs.app/Contents/Resources/lisp/play | /Applications/Emacs.app/Contents/Resources/lisp/org | /Applications/Emacs.app/Contents/Resources/lisp/nxml | /Applications/Emacs.app/Contents/Resources/lisp/net | /Applications/Emacs.app/Contents/Resources/lisp/mh-e | /Applications/Emacs.app/Contents/Resources/lisp/mail | /Applications/Emacs.app/Contents/Resources/lisp/leim | /Applications/Emacs.app/Contents/Resources/lisp/language | /Applications/Emacs.app/Contents/Resources/lisp/international | /Applications/Emacs.app/Contents/Resources/lisp/image | /Applications/Emacs.app/Contents/Resources/lisp/gnus | /Applications/Emacs.app/Contents/Resources/lisp/eshell | /Applications/Emacs.app/Contents/Resources/lisp/erc | /Applications/Emacs.app/Contents/Resources/lisp/emulation | /Applications/Emacs.app/Contents/Resources/lisp/emacs-lisp | /Applications/Emacs.app/Contents/Resources/lisp/cedet | /Applications/Emacs.app/Contents/Resources/lisp/calendar | /Applications/Emacs.app/Contents/Resources/lisp/calc | /Applications/Emacs.app/Contents/Resources/lisp/obsolete |

* selection candidates and search
** orderless

#+BEGIN_SRC emacs-lisp
(use-package prot-orderless
  :demand
  :config
  (setq prot-orderless-default-styles
        '(orderless-prefixes
          orderless-literal
          orderless-strict-leading-initialism
          orderless-regexp
          orderless-flex))
  (setq prot-orderless-alternative-styles
        '(orderless-literal
          orderless-prefixes
          orderless-strict-leading-initialism
          orderless-regexp)))

(use-package orderless
  :ensure t
  :demand
  :after prot-orderless
  :config
  (setq orderless-component-separator " +")
  (setq orderless-matching-styles prot-orderless-default-styles)
  (setq orderless-style-dispatchers
        '(prot-orderless-literal-dispatcher
          prot-orderless-initialism-dispatcher))
  ;; SPC should never complete: use it for `orderless' groups.
  :bind (:map minibuffer-local-completion-map
              ("SPC" . nil)))
#+END_SRC

#+RESULTS:
** selectrum

#+BEGIN_SRC emacs-lisp
(use-package selectrum
  :straight t
  :config
  (set-face-attribute 'selectrum-current-candidate nil :background (doom-darken "#c792ea" 0.6))
  (selectrum-mode +1)
)
#+END_SRC

#+RESULTS:
: t

*** prescient

selectrum provides no smart sorting OOTB, for which we use =prescient.el=:

#+BEGIN_SRC emacs-lisp
;; to make sorting and filtering more intelligent
(straight-use-package 'selectrum-prescient)
(selectrum-prescient-mode +1)
#+END_SRC

#+RESULTS:
: t

** embark

#+BEGIN_SRC emacs-lisp
(use-package embark
  ;; Note that this gets only the main library.  That repo contains
  ;; other packages as well (which are small *.el files that are
  ;; distributed separately).
  :straight (embark :host github
                    :repo "oantolin/embark"
                    :branch "master"
                    :files ("embark.el"))
  :demand
  :diminish embark-collect-zebra-minor-mode
  :after prot-minibuffer
  :config
  (setq embark-collect-initial-view-alist
        '((file . list)
          (buffer . list)
          (symbol . list)
          (line . list)
          (xref-location . list)
          (kill-ring . zebra)
          (t . list)))
  (setq embark-collect-live-update-delay 0.5)
  (setq embark-collect-live-initial-delay 0.8)

  ;; Please don't read too much into the names of those faces.  Just
  ;; green and yellow.
  (setq embark-action-indicator (propertize "Act" 'face 'success))
  (setq embark-become-indicator (propertize "Become" 'face 'warning))

  ;; ;; NOTE: I keep this around for when I do videos, otherwise I do not
  ;; ;; use it.  It requires `which-key' to display key hints.
  ;; (setq embark-action-indicator
  ;;       (lambda (map)
  ;;         (which-key--show-keymap "Embark" map nil nil 'no-paging)
  ;;         #'which-key--hide-popup-ignore-command)
  ;;       embark-become-indicator embark-action-indicator)
  :hook ((minibuffer-setup-hook . embark-collect-completions-after-input)
         (embark-post-action-hook . embark-collect--update-linked)
         (embark-collect-mode-hook . prot-embark-completions-cursor))
  :bind (("C-r" . embark-act)
         :map minibuffer-local-completion-map
         ("C-r" . embark-act)
         ("C-." . embark-act-noexit)
         ("C->" . embark-become)
         ("M-q" . embark-collect-toggle-view) ; parallel of `fill-paragraph'
         :map embark-collect-mode-map
         ("C-r" . embark-act)
         ("C-." . embark-act-noexit)
         ("r" . embark-act)
         ("." . embark-act-noexit)
         ("M-q" . embark-collect-toggle-view)
         :map embark-symbol-map
         ("." . embark-find-definition)
         ("k" . describe-keymap)))

;; Integration with Consult.  Note that the package is `embark-consult',
;; but because it comes from the same repo as Embark I prefer to use
;; this straight.el directive (check the main embark package above).
(use-package embark-consult
  :straight (embark-consult :host github
                            :repo "oantolin/embark"
                            :branch "master"
                            :files ("embark-consult.el"))
  :demand
  :after (embark consult)
  ;; ;; Use the hook, or check `prot-embark-consult-preview-toggle'.
  ;; :hook (embark-collect-mode-hook . embark-consult-preview-minor-mode)
  :bind (:map embark-collect-mode-map
         ("C-j" . embark-consult-preview-at-point)))

(use-package prot-embark
  :straight (:type built-in)
  :demand
  :after embark
  :hook ((minibuffer-exit-hook . prot-embark-clear-live-buffers)
         (embark-collect-post-revert-hook . prot-embark-collect-fit-window)
         (embark-collect-mode-hook . prot-embark-hl-line)
         (embark-collect-mode-hook . prot-embark-display-line-numbers))
  ;; NOTE: to switch to the live collection buffer, I also use
  ;; `prot-minibuffer-focus-mini-or-completions' which is bound to
  ;; "s-v".
  :bind (:map embark-collect-mode-map
         ("h" . prot-simple-describe-symbol)  ; from `prot-simple.el'
         ("C-g" . prot-embark-keyboard-quit)
         ("C-k" . prot-embark-collection-kill-line)
         ("C-M-n" . prot-embark-completions-act-next)
         ("C-M-p" . prot-embark-completions-act-previous)
         ("C-M-j" . prot-embark-completions-act-current)
         ("C-M-v" . prot-embark-consult-preview-toggle) ; "view", "visualise" mnemonic
         ("C-n" . prot-embark-next-line-or-mini)
         ("C-p" . prot-embark-previous-line-or-mini)
         ("M-F" . prot-embark-collection-flush-lines) ; M-S-f like M-S-5 (M-%)
         ("M-K" . prot-embark-collection-keep-lines)  ; same principle as right above
         :map minibuffer-local-completion-map
         ("C-n" . prot-embark-switch-to-completions-top)
         ("C-p" . prot-embark-switch-to-completions-bottom)
         ("C-l" . prot-embark-completions-toggle)))
#+END_SRC

#+RESULTS:
: prot-embark-completions-toggle

** marginalia

#+BEGIN_SRC emacs-lisp
(use-package marginalia
  :straight (:host github :repo "minad/marginalia" :branch "main")
  :demand
  :config
  (setq marginalia-annotators
        '(marginalia-annotators-heavy
          marginalia-annotators-light))
  (marginalia-mode 1))
#+END_SRC

#+RESULTS:
: t

** consult

#+BEGIN_SRC emacs-lisp
(use-package consult
  :ensure t
  :demand
  :config
  (setq consult-line-numbers-widen t)
  (setq completion-in-region-function #'consult-completion-in-region)
  (setq consult-async-min-input 3)
  (setq consult-async-input-debounce 0.5)
  (setq consult-async-input-throttle 0.8)
  (setq consult-narrow-key ">")

  ;; configure a function which returns the project root directory
  (autoload 'projectile-project-root "projectile")
  (setq consult-project-root-function #'projectile-project-root)

  ;; NOTE: check `embark-consult' for previews that can be used with the
  ;; default minibuffer and Embark collections.
  :bind (("C-x M-:" . consult-complex-command)
         ("C-x M-m" . consult-minor-mode-menu)
         ("C-x M-k" . consult-kmacro)
         ("M-g g" . consult-goto-line)
         ("M-g M-g" . consult-goto-line)
         ("M-X" . consult-mode-command)
         ("M-K" . consult-keep-lines)  ; M-S-k is similar to M-S-5 (M-%)
         ("M-s f" . consult-find)
         ("M-s g" . consult-grep)
         ("M-s m" . consult-mark)
         ("C-j" . consult-buffer)
         ("C-x b" . consult-buffer)
         :map consult-narrow-map
         ("?" . consult-narrow-help)))

;; enforce the switch-buffer binding
(bind-key* "C-j" 'consult-buffer)

(use-package prot-consult
  ;; :after (consult prot-pulse)
  :after (consult)
  :config
  (setq consult-project-root-function #'prot-consult-project-root)
  (setq prot-consult-add-advice-set-hooks t)
  (setq prot-consult-command-centre-list
        '(consult-line
          prot-consult-line
          consult-mark))
  (setq prot-consult-command-top-list
        '(consult-outline
          consult-imenu
          prot-consult-outline
          prot-consult-imenu))
  (prot-consult-set-up-hooks-mode 1)
  :bind (("M-s i" . prot-consult-imenu)
         ("M-s s" . prot-consult-outline)    ; M-s o is `occur'
         ("M-s y" . prot-consult-yank)
         ("M-s l" . prot-consult-line)))
#+END_SRC

#+RESULTS:


* minibuffer

#+BEGIN_SRC emacs-lisp
(use-package prot-minibuffer
  :demand
  :bind (("s-v" . prot-minibuffer-focus-mini-or-completions)
         :map completion-list-mode-map
         ("M-v" . prot-minibuffer-focus-mini)
         ("h" . prot-simple-describe-symbol) ; from `prot-simple.el'
         ;; Those are DE FACTO DEPRECATED generic actions for the
         ;; "*Completions*" buffer.  I normally use `embark' and its own
         ;; buffers.
         ("w" . prot-minibuffer-completions-kill-symbol-at-point)
         ("i" . prot-minibuffer-completions-insert-symbol-at-point)
         ("j" . prot-minibuffer-completions-insert-symbol-at-point-exit))
  :hook (minibuffer-setup-hook . prot-minibuffer-mini-cursor))

(use-package minibuffer
  :demand
  :after prot-minibuffer
  :config
  (setq completion-styles '(orderless partial-completion))
  (setq completion-category-defaults nil)
  (setq completion-cycle-threshold 3)
  (setq completion-flex-nospace nil)
  (setq completion-pcm-complete-word-inserts-delimiters t)
  (setq completion-pcm-word-delimiters "-_./:| ")
  (setq completion-show-help nil)
  (setq completion-auto-help nil)
  (setq completion-ignore-case t)
  (setq-default case-fold-search t)   ; For general regexp

  ;; The following two are updated in Emacs 28.  They concern the
  ;; *Completions* buffer.  Note that I actually do not use that buffer,
  ;; because I rely on Embark's version of it.
  (setq completions-format 'one-column)
  (setq completions-detailed t)

  (setq read-buffer-completion-ignore-case t)
  (setq read-file-name-completion-ignore-case t)

  (setq enable-recursive-minibuffers t)
  (setq read-answer-short t)
  (setq resize-mini-windows t)
  (setq minibuffer-eldef-shorten-default t)

  (file-name-shadow-mode 1)
  (minibuffer-depth-indicate-mode 1)
  (minibuffer-electric-default-mode 1)

  ;; Defines, among others, aliases for common minibuffer commands to
  ;; Super-KEY.  Normally these should go in individual package
  ;; declarations, but their grouping here makes things easier to
  ;; understand.  Besides, they are related to the minibuffer.
  :bind (("s-b" . switch-to-buffer)
         ("s-B" . switch-to-buffer-other-window)
         ("s-f" . find-file)
         ("s-F" . find-file-other-window)
         ("s-d" . dired)
         ("s-D" . dired-other-window)
         :map minibuffer-local-completion-map
         ("C-j" . exit-minibuffer)
         ("<tab>" . minibuffer-force-complete)
         ;; De facto deprecated as I use Embark and its own completions'
         ;; buffer.
         :map completion-list-mode-map
         ("n" . next-line)
         ("p" . previous-line)
         ("f" . next-completion)
         ("b" . previous-completion)))
#+END_SRC

#+RESULTS:
: previous-completion

* configuring windows
** manage window view

#+BEGIN_SRC emacs-lisp
(defvar ctl-x-map-transient nil
  "Transient keymap for C-x commands.
The normal global definition of the character C-x indirects to this keymap.")
;; (define-prefix-command  (kbd "C-x")  ctl-x-map-transient)



(setq ctl-x-map-transient (let ((map (make-sparse-keymap)))
                            (define-key map "p" `move-windows)
                            (define-key map "n" `move-windows)
                            (define-key map "g" `move-windows)
                            (define-key map "0" 'delete-window)
                            (define-key map "q" 'delete-window)
                            (define-key map "1" 'delete-other-windows)
                            (define-key map "2" 'split-window-below)
                            (define-key map "3" 'split-window-right)
                            map))


(defun move-windows ()
  (interactive)
  (let* ((base (event-basic-type last-command-event))
         (step (pcase base
                 (?p -1)
                 (?n 1)
                 (?g 0))))
    (if (not (= step 0))
        (progn
          (message "Use p and n to move back and forwards between windows, g to quit")
          (other-window step)
          (set-transient-map ctl-x-map-transient)
          ))))
(global-set-key (kbd "C-x p")  `move-windows)
(global-set-key (kbd "C-x n")  `move-windows)


#+END_SRC

#+RESULTS:
: move-windows
** changing size
#+BEGIN_SRC emacs-lisp
(defun resize-window (inc)
  (interactive "p")
  (let* ((base (event-basic-type last-command-event))
           (step (pcase base
                   ((or ?f ?n) inc)
                   ((or ?b ?p) (- inc))))
           (horizontal (pcase base
                         ((or ?f ?b) t))))
      (enlarge-window step horizontal))
    (message "Use f,b,n,p to adjust window size")
    (set-transient-map (let ((map (make-sparse-keymap)))
    (define-key map "f" 'resize-window);;(lambda () (interactive "p") (resize-window 1)))
    (define-key map "b" 'resize-window)
    (define-key map "n" 'resize-window)
    (define-key map "p" 'resize-window)
    map)))

(global-set-key (kbd "C-x w f") (lambda () (interactive) (resize-window 1)))
(global-set-key (kbd "C-x w b") (lambda () (interactive) (resize-window 1)))
(global-set-key (kbd "C-x w n") (lambda () (interactive) (resize-window 1)))
(global-set-key (kbd "C-x w p") (lambda () (interactive) (resize-window 1)))
#+END_SRC

* ssh shortcuts

fns to reset directories to local:
#+BEGIN_SRC emacs-lisp
(defun local ()
  (interactive)
  (setq default-directory "/Users/jeroen"))

(defun reset-default-directory ()
  (interactive)
  (setq-local default-directory (file-name-directory (buffer-file-name))))

(defun open-shell-in-directory (directory &optional buffername)
  (interactive)
  (message "osid")
  (message directory)
  (message buffername)
  (with-temp-buffer
    (setq default-directory directory)
    (shell buffername)
    )
)
#+END_SRC

#+RESULTS:
: open-shell-in-directory

add remote endpoints

#+BEGIN_SRC emacs-lisp
(setq ssh-config '(
                   ("fxr" "/ssh:jeroen@168.119.165.84:")
                   ("lisa-dl" "/ssh:lgpu0348@lisa.surfsara.nl:")
                  ))

(dolist (elt ssh-config)
  (define-named-lambda
    (nth 0 elt)
    (lambda (directory)
      (interactive)
      (setq default-directory directory))
    '((nth 1 elt))
    )
  (define-named-lambda
    (s-concat "shell-" (nth 0 elt))
    (lambda (name directory)
      (interactive)
      (open-shell-in-directory directory (s-concat "*shell-" name "*")))
    elt
    )
)
#+END_SRC

#+RESULTS:

* better keybindings

# bind § key to emulate _

#+BEGIN_SRC emacs-lisp
;; (global-set-key (kbd "C-§") (kbd "_"))
;; (defun exec-underscore () (interactive) (execute-kbd-macro (kbd "C-§")))
;; (defun exec-hyphen () (interactive) (execute-kbd-macro (kbd "-")))
;; (global-set-key (kbd "-") 'exec-underscore)
;; (global-set-key (kbd "_") 'exec-hyphen)
#+END_SRC

#+RESULTS:

copy/cut entire line if no region selected:
#+BEGIN_SRC emacs-lisp
(defun slick-cut (beg end)
  (interactive
   (if mark-active
       (list (region-beginning) (region-end))
     (message "Cut line")
     (list (line-beginning-position) (line-beginning-position 2)))))

(advice-add 'kill-region :before #'slick-cut)

(defun slick-copy (beg end)
  (interactive
   (if mark-active
       (list (region-beginning) (region-end))
     (message "Copied line")
     (list (line-beginning-position) (line-beginning-position 2)))))

(advice-add 'kill-ring-save :before #'slick-copy)
#+END_SRC

#+RESULTS:

move windows with arrow keys (i know...)

#+BEGIN_SRC emacs-lisp
(bind-key* "M-<left>"  'windmove-left)
(bind-key* "M-<right>" 'windmove-right)
(bind-key* "M-<up>"    'windmove-up)
(bind-key* "M-<down>"  'windmove-down)
#+END_SRC

#+RESULTS:
: windmove-down

open shell with =s-s=:

#+BEGIN_SRC emacs-lisp
(bind-key* "s-s" 'shell)
#+END_SRC

#+RESULTS:
: shell

* auto-fill-mode

#+BEGIN_SRC emacs-lisp
(auto-fill-mode 1)
#+END_SRC

#+RESULTS:
: yas--auto-fill

* which-key

#+BEGIN_SRC emacs-lisp
(which-key-mode 1)
#+END_SRC

#+RESULTS:
: t

* which-function-mode

#+begin_src emacs-lisp
(which-function-mode)
#+end_src

* ibuffer

[paul]
Let's try to get the ibuffer bound to =C-x C-b=, and have it open in the same
window, instead of a new window.

#+BEGIN_SRC emacs-lisp
  (setq ibuffer-use-other-window nil)
  (global-set-key (kbd "C-x C-b") `ibuffer)

#+END_SRC

#+RESULTS:
: ibuffer

[paul]
Unlike the regular buffer menu, =ibuffer= filters the buffers when you hit =RET=
when you are in the =Size Mode= column. Let's change this behaviour so that
="RET"= still visits the buffer, but pressing =f= causes it to filter still.

#+BEGIN_SRC emacs-lisp
(defvar ibuffer-mode-name-map
  (let ((map (make-sparse-keymap)))
    (define-key map [(mouse-2)] 'ibuffer-mouse-filter-by-mode)
    (define-key map (kbd "f") 'ibuffer-interactive-filter-by-mode)
    (define-key map (kbd "RET") 'ibuffer-visit-buffer)
    map))
#+END_SRC

#+RESULTS:
: ibuffer-mode-name-map

* swiper
#+BEGIN_SRC emacs-lisp
  (use-package swiper
    :ensure t
    :config (global-set-key (kbd "C-s") 'swiper))
#+END_SRC
* counsel
#+BEGIN_SRC emacs-lisp
  ;; (use-package counsel
  ;;   :ensure t
  ;;   :config
  ;;   ;; (global-set-key (kbd "M-x")         'counsel-M-x)
  ;;   ;; (global-set-key (kbd "C-x C-f")     'counsel-find-file)
  ;;   (global-set-key (kbd "C-h S")       'counsel-info-lookup-symbol)
  ;;   (global-set-key (kbd "C-c 8 <ret>") 'counsel-unicode-char)

  ;;   (global-set-key (kbd "C-c g") 'counsel-git)
  ;;   (global-set-key (kbd "C-c j") 'counsel-git-grep)
  ;;   ;; (global-set-key (kbd "C-c k") 'counsel-rg)
  ;;   (global-set-key (kbd "C-x l") 'counsel-locate)

  ;;   (setq counsel-find-file-ignore-regexp "\\*.fasl$"))
#+END_SRC
* ivy
#+BEGIN_SRC emacs-lisp
;; (use-package ivy
;;   :ensure t
;;   :config
;;   (ivy-mode 1)
;;   (setq ivy-use-virtual-buffers t
;;         ivy-count-format "%d/%d "
;;         ivy-wrasp t
;;         ivy-magic-tilde nil)
;;   (global-set-key (kbd "C-c C-r") 'ivy-resume))
#+END_SRC

* dired

#+BEGIN_SRC emacs-lisp
  (require 'dired-x)

  (setq dired-omit-files
        (concat dired-omit-files
                "\\|"
                (regexp-orrify "\\.orgx$"
                               "^\.DS_Store$"
                               "^__MACOSX$"
                               "\\.pyc$"
                               "\\.pyo$"
                               "^__pycache__"
                               ".ipynb_checkpoints"
                               "\\.lprof$"
                               "\\.bak$"
                               "^ltximg$"
                               "^\\.~lock\\."
                               "^!.*pdf$"
                               "\\.~.*#")))

  (add-hook 'dired-mode-hook
            #'(lambda ()
                (setq dired-guess-shell-alist-user
                      '(("\\.e?ps$" "gv" "lpr")
                        ("\\.pdf$" "mupdf" "xpdf" "lp" "acroread")
                        ("\\.mobi$" "ebook-viewer")
                        ("\\.epub$" "ebook-viewer")
                        ("\\.djvu$" "ebook-viewer")
                        ("\\.csv$" "loffice" "gnumeric")
                        ("\\.docx?$" "loffice")
                        ("\\.xlsx?$" "loffice" "gnumeric")
                        ("\\.pptx?$" "loffice")
                        ("\\.od[spt]$" "loffice")
                        ("\\.divx$" "mplayer")
                        ("\\.flv$" "mplayer")
                        ("\\.avi$" "mplayer")
                        ("\\.mpg$" "mplayer")
                        ("\\.mp4$" "mplayer")
                        ("\\.wmv$" "mplayer")
                        ("\\.mkv$" "mplayer")
                        ("\\.mov$" "mplayer")
                        ("\\.webm$" "mplayer")
                        ("Flash......$" "mplayer")
                        ("mplay......$" "mplayer")
                        ("\\.p[bgpn]m$" "geeqie" "display")
                        ("\\.gif$" "geeqie" "display")
                        ("\\.tif$" "geeqie" "display")
                        ("\\.png$" "geeqie" "display")
                        ("\\.jpe?g$" "geeqie" "display")
                        ("\\.svg$" "geeqie" "display")
                        ("\\.e?ps.g?z$" "gunzip -qc * | gv -"
                         (concat
                          "gunzip"
                          (if dired-guess-shell-gzip-quiet " -q")))
                        ("\\.e?ps.Z$" "zcat * | gv -"
                         (concat "znew"
                                 (if dired-guess-shell-gzip-quiet " -q")
                                 " " dired-guess-shell-znew-switches))
                        ("viewapp.asp" "xpdf"))
                      dired-listing-switches "-alh")
                (local-set-key "\C-c\C-zf" 'browse-url-of-dired-file)
                (dired-omit-mode)
                (whitespace-mode -1)))

    ;; Auto complete with ignore case
    (setq-default read-buffer-completion-ignore-case t)
    (setq-default read-file-name-completion-ignore-case t)
#+END_SRC

#+RESULTS:
: t

show filesize as kb, mb, etc:

#+BEGIN_SRC emacs-lisp
(setq dired-listing-switches "-alh")
#+END_SRC

#+RESULTS:
: -alh

* expand-region
#+BEGIN_SRC emacs-lisp
(use-package expand-region
  :bind ("C-=" . er/expand-region))
#+END_SRC
* etc
** keybindings

#+BEGIN_SRC emacs-lisp
;; (global-set-key (kbd "C-c 3") 'browse-url-at-point)
(global-set-key (kbd "C-c b") 'bury-buffer)
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "C-c t") 'tramp-cleanup-this-connection)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(add-hook 'emacs-lisp-mode-hook
          (lambda ()
            (local-set-key (kbd "C-c C-c") 'eval-buffer)))
#+END_SRC

#+RESULTS:
: er/expand-region

** Find-grep functionality
#+BEGIN_SRC emacs-lisp
(defun find-pattern-in-dir ()
  (interactive)
  (let* ((dir-name (read-directory-name "Directory to look in: "))
         (extensions (seq-map 'file-name-extension (directory-files dir-name)))
         (file-pattern (read-from-minibuffer "Files to match: " "*.org"))
         (grep-pattern (read-from-minibuffer "Grep pattern: ")))
    (shell-command (format "find %s -name  '%s' | xargs grep %s" dir-name file-pattern grep-pattern))))
#+END_SRC

** Replace-string defun only
Let's write a function that replaces a string only in current defun definition
#+BEGIN_SRC emacs-lisp
(defun replace-string-defun ()
  (interactive)
  (save-window-excursion
    (narrow-to-defun)
    (mark-whole-buffer)
    (call-interactively 'replace-string)
    (widen)))
#+END_SRC

#+RESULTS:
: replace-string-defun

** Comment-line
#+BEGIN_SRC emacs-lisp
(defun comment-dwim-or-line ()
  (interactive)
  "Comments if region selected, else comment line"
   (if (use-region-p)
   (save-excursion (call-interactively 'comment-dwim))
   (save-excursion (call-interactively 'comment-line)))

)
(global-set-key (kbd "M-;") 'comment-dwim-or-line)
#+END_SRC

#+RESULTS:
: comment-dwim-or-line

** wrap-region
#+BEGIN_SRC emacs-lisp
(use-package wrap-region
  :diminish)
(wrap-region-global-mode)
(wrap-region-add-wrapper "`" "`")
(wrap-region-add-wrapper "'" "'")
(wrap-region-add-wrapper "|" "|")
;; (wrap-region-add-wrapper "=" "=")
(wrap-region-add-wrapper "$" "$")
(wrap-region-global-mode t)
#+END_SRC

** format-arg
#+BEGIN_SRC emacs-lisp
(defun format-arg ()
  (interactive)
  (if (use-region-p)
      (save-excursion (goto-char (region-beginning))
                      (insert "(format \"%s\" ")
                      (goto-char (region-end))
                      (insert  ")")
                      ;; (let ((arg (extract-rectangle (region-beginning) (region-end))))
                      ;;   (insert (concat "(format \"%s\" " (format "%s)" arg))))
                      )))

;; (format "%s" fdsf
;; (format "%s" fdf

(defun print-arg-python ()
  (interactive)
  (if (use-region-p)
      (let ((msg (read-from-minibuffer "Message to print with: ")))
      (save-excursion (goto-char (region-beginning))
                      (insert "print(f\"")
                      (insert (format "%s: {" msg))
                      (goto-char (region-end))
                      (insert  "}\")")
                      ;; (let ((arg (extract-rectangle (region-beginning) (region-end))))
                      ;;   (insert (concat "(format \"%s\" " (format "%s)" arg))))
                      ))))

(defun print-arg ()
  (interactive)
    (cond
     ((string-match-p (regexp-quote "emacs-lisp") (symbol-name major-mode))
      (call-interactively 'print-arg-elisp))
      ((string-match-p (regexp-quote "python") (symbol-name major-mode))
      (call-interactively 'print-arg-python))
))



(defun print-arg-elisp ()
  (interactive)
  (if (use-region-p)
      (save-excursion (goto-char (region-beginning))
                      (insert "(message (format \"%s\" ")
                      (goto-char (region-end))
                      (insert  "))")
                      ;; (let ((arg (extract-rectangle (region-beginning) (region-end))))
                      ;;   (insert (concat "(format \"%s\" " (format "%s)" arg))))
                      )))

(defalias  'farg 'format-arg)
(defalias  'parg 'print-arg)

#+END_SRC

#+RESULTS:
: parg

** copy and comment
#+BEGIN_SRC emacs-lisp
(defun copy-and-comment ()
  (interactive)
  (if (use-region-p)
      (let ((beg (region-beginning))
            (end (region-end)))
        (call-interactively 'kill-ring-save)
        (call-interactively (lambda () (interactive) (comment-region beg end)))
      )))
(global-set-key (kbd "C-M-;") 'copy-and-comment)
#+END_SRC

#+RESULTS:
: copy-and-comment

** Indent rigidly without aRrOw KEyS
#+BEGIN_SRC emacs-lisp
(setq indent-rigidly-map
      (let ((map (make-sparse-keymap)))
        (define-key map [left]  'indent-rigidly-left)
        (define-key map (kbd "C-M-b")  'indent-rigidly-left)
        (define-key map [right] 'indent-rigidly-right)
        (define-key map (kbd "C-M-f") 'indent-rigidly-right)
        (define-key map [S-right] 'indent-rigidly-right-to-tab-stop)
        map)
      )
#+END_SRC

** set default dir of
#+BEGIN_SRC emacs-lisp
(defun set-default-dir-of ()
  (interactive)
  (let ((b (read-buffer "Select buffer: " (buffer-list))))
    (setq default-directory (buffer-file-name (get-buffer (read-buffer "check" nil nil (lambda (b) (not (null (buffer-file-name (cdr b)))))))))
    ))
#+END_SRC

#+RESULTS:
: set-default-dir-of


drag-stuff

#+BEGIN_SRC emacs-lisp
(load-org "drag-stuff.org")
#+END_SRC

add org elpa to package archive
#+BEGIN_SRC emacs-lisp
  (require 'package)
  (add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
#+END_SRC

#+RESULTS:
: ((melpa . http://melpa.org/packages/) (gnu . https://elpa.gnu.org/packages/) (melpa . https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/) (melpa . https://stable.melpa.org/packages/) (org . https://orgmode.org/elpa/))

enable org-mode auto-fill-mode and org-indent-mode automatically:

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'auto-fill-mode)
(add-hook 'org-mode-hook 'org-indent-mode)
#+END_SRC

#+RESULTS:
| org-indent-mode | auto-fill-mode | ob-ipython-auto-configure-kernels | (lambda nil (setq inhibit-read-only 1) (wrap-region-add-wrapper = =) (wrap-region-add-wrapper ~ ~) (wrap-region-add-wrapper + +) (wrap-region-add-wrapper / /) (wrap-region-add-wrapper * *) (wrap-region-add-wrapper _ _) (wrap-region-add-wrapper |   | ) (modify-syntax-entry 42 ") (modify-syntax-entry 124 ") (org-bullets-mode)) | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | org-journal-update-auto-mode-alist |



#+BEGIN_SRC emacs-lisp
;; (defun move-line-up ()
;;   "Move up the current line."
;;   (interactive)
;;   (transpose-lines 1)
;;   (forward-line -2)
;;   (indent-according-to-mode))

;; (defun move-line-down ()
;;   "Move down the current line."
;;   (interactive)
;;   (forward-line 1)
;;   (transpose-lines 1)
;;   (forward-line -1)
;;   (indent-according-to-mode))

;; (global-set-key [(meta up)]  'move-line-up)
;; (global-set-key [(meta down)]  'move-line-down)

(defun duplicate-line()
  (interactive)
  (move-beginning-of-line 1)
  (kill-line)
  (yank)
  (open-line 1)
  (next-line 1)
  (yank)
)
(global-set-key (kbd "C-c C-d") 'duplicate-line)


(defun emacs-gitignore  ()
  (interactive)
  (let ((fullpath (string-join (list default-directory ".gitignore"))))
    (if (file-exists-p fullpath)
        (progn
          (shell-command-to-string "curl 'https://raw.githubusercontent.com/github/gitignore/master/Global/Emacs.gitignore' >> .gitignore")
          (message (format "Added emacs-gitignore in %s" default-directory))))))

  ;; (yank)

  ;;     (shell-command-to-string "curl 'https://raw.githubusercontent.com/github/gitignore/master/Global/Emacs.gitignore' >> .gitignore")
  ;; (message (format "Added gitignore in %s" default-directory))
;; )
#+END_SRC

#+RESULTS:
: emacs-gitignore

#+BEGIN_SRC emacs-lisp
;;  (require 'hydra)
;; (defhydra hydra-zoom (global-map "M")
;;   "zoom"
;;   ("g" text-scale-increase "in")
;;  ("l" text-scale-decrease "out"))
;; (drag-stuff-mode)
;; (defhydra hydra-zoom (global-map "<f2>")
;;   "zoom"
;;   ("g" text-scale-increase "in")
;;   ("l" text-scale-decrease "out"))
(define-key indent-rigidly-map (drag-stuff--kbd 'left) 'drag-stuff-left)
(define-key indent-rigidly-map (kbd "C-p") 'drag-stuff-up)
(define-key indent-rigidly-map (kbd "C-n") 'drag-stuff-down)
(define-key indent-rigidly-map (kbd "C-f") 'drag-stuff-right)
(define-key indent-rigidly-map (kbd "C-b") 'drag-stuff-left)
(drag-stuff-mode)
#+END_SRC

#+RESULTS:
: t

** Search through buffers
#+BEGIN_SRC emacs-lisp
(defun occur-selection ()
  (interactive)
  (when (region-active-p)
    (let (deactivate-mark)
      (occur (regexp-quote (buffer-substring (region-beginning) (region-end)))))))
(global-set-key [(meta o)] 'occur-selection)

#+END_SRC

#+RESULTS:
: occur-selection

** many configurations
miscellaneous configurations
#+BEGIN_SRC emacs-lisp
;; (savehist-mode 1)

;; ;; Lazy prompting. Change "yes or no" to "y or n"
;; ;; http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html
(fset 'yes-or-no-p 'y-or-n-p)

(setq-default
fill-column 79
standard-indent 2

 ;;  ;; comment for now
;;  ;; tab-always-indent 'complete
;;  ;; indent-tabs-mode nil

;;  sentence-end-double-space nil
;;  indicate-empty-lines t

;;  european-calendar-style t
;;  calendar-date-style 'european
;;  calendar-week-start-day 1
;;  diary-file "~/.diary"

;;  display-time-24hr-format t
;;  display-time-day-and-date t
;;  display-time-string-forms
;;  '((if (and (not display-time-format) display-time-day-and-date)
;;  (format-time-string "%a %b %e " now) "")
;;    (format-time-string (or display-time-format
;;          (if display-time-24hr-format "%H:%M" "%-I:%M%p"))
;;      now))
;;  calendar-time-display-form
;;  '(24-hours ":" minutes
;;       (if time-zone " (") time-zone (if time-zone ")"))


;;  delete-old-versions t
;;  vc-make-backup-files t
;;  backup-directory-alist '((".*" . "~/.emacs.d/emacs-backups"))

;;  mail-user-agent 'gnus-user-agent
;;  ps-paper-type 'a4

;;  ediff-split-window-function 'split-window-horizontally
;;  ediff-window-setup-function 'ediff-setup-windows-plain

 enable-recursive-minibuffers t
;;  debug-on-error nil

;;  compile-command "remake install"

;;  aurel-download-directory "~/code/src/aur"

;;  async-shell-command-buffer 'new-buffer ; Don't ask.
;;  display-buffer-alist '(("*Async Shell Command*" . (display-buffer-no-window)))
;;  ibuffer-use-other-window nil
;;  Man-width 80
;;  Man-notify-method 'aggressive

;;  eshell-prompt-function #'(lambda () "$ ")
 )

;; ;; (add-to-list 'ibuffer-never-show-predicates "^\*Async")

;; (dolist (mode '(scroll-bar-mode))
;;   (if (fboundp mode) (funcall mode -1)))

;; ;; Edit from  chrome
;; ;; (edit-server-start)

;; ;; Save point position between sessions
;; ;; (use-package saveplace
;; ;;   :ensure t
;; ;;   :config
;; ;;   (setq-default save-place t)
;; ;;   (setq save-place-file (expand-file-name ".places" user-emacs-directory)))
#+END_SRC

#+RESULTS:
: t

** delete line but don't kill
#+BEGIN_SRC emacs-lisp
(defun kill-line (&optional arg)
  "Kill the rest of the current line; if no nonblanks there, kill thru newline.
With prefix argument ARG, kill that many lines from point.
Negative arguments kill lines backward.
With zero argument, kills the text before point on the current line.

When calling from a program, nil means \"no arg\",
a number counts as a prefix arg.

To kill a whole line, when point is not at the beginning, type \
\\[move-beginning-of-line] \\[kill-line] \\[kill-line].

If `show-trailing-whitespace' is non-nil, this command will just
kill the rest of the current line, even if there are no nonblanks
there.

If option `kill-whole-line' is non-nil, then this command kills the whole line
including its terminating newline, when used at the beginning of a line
with no argument.  As a consequence, you can always kill a whole line
by typing \\[move-beginning-of-line] \\[kill-line].

If you want to append the killed line to the last killed text,
use \\[append-next-kill] before \\[kill-line].

If the buffer is read-only, Emacs will beep and refrain from deleting
the line, but put the line in the kill ring anyway.  This means that
you can use this command to copy text from a read-only buffer.
\(If the variable `kill-read-only-ok' is non-nil, then this won't
even beep.)"
  (interactive "P")
  (delete-region (point)
         ;; It is better to move point to the other end of the kill
         ;; before killing.  That way, in a read-only buffer, point
         ;; moves across the text that is copied to the kill ring.
         ;; The choice has no effect on undo now that undo records
         ;; the value of point from before the command was run.
               (progn
                 (if arg
         (forward-visible-line (prefix-numeric-value arg))
       (if (eobp)
           (signal 'end-of-buffer nil))
       (let ((end
        (save-excursion
          (end-of-visible-line) (point))))
         (if (or (save-excursion
             ;; If trailing whitespace is visible,
             ;; don't treat it as nothing.
             (unless show-trailing-whitespace
         (skip-chars-forward " \t" end))
             (= (point) end))
           (and kill-whole-line (bolp)))
       (forward-visible-line 1)
           (goto-char end))))
     (point))))
#+END_SRC

#+RESULTS:
: kill-line

* magit
#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :bind (
         ("C-x g" . magit-status)
         :map magit-mode-map
         ("C-j" . consult-buffer))
  :diminish magit-minor-mode)
#+END_SRC
* yasnippet

#+BEGIN_SRC emacs-lisp
;; (add-hook 'yas-minor-mode-hook (lambda () (yas-activate-extra-mode
;;           'fundamental-mode)))
;; (use-package yasnippet
;;   :config
;;   (yas-global-mode 1))

;; (add-hook 'yas-minor-mode-hook
;;           (lambda ()
;;             (yas-activate-extra-mode 'fundamental-mode)))
(use-package yasnippet
  :diminish)
(yas-global-mode 1)
#+END_SRC

#+RESULTS:
: t

* multiple-cursors
#+BEGIN_SRC emacs-lisp
(bind-keys* ((kbd "C-.") . mc/mark-next-like-this)
            ((kbd "C-,") . mc/mark-previous-like-this)
            ((kbd "C-M-.") . mc/unmark-next-like-this)
            ((kbd "C-M-,") . mc/unmark-previous-like-this)
             ((kbd "C-c C-,") . mc/mark-all-like-this))
#+END_SRC

#+RESULTS:
: mc/mark-all-like-this

* projectile

#+BEGIN_SRC emacs-lisp
(use-package projectile
  :diminish
  :ensure t)
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(projectile-mode +1)
#+END_SRC

#+RESULTS:
: t

* rails

** projectile-rails

projectile-rails is used for navigation inside a rails project.

#+BEGIN_SRC emacs-lisp
(use-package projectile-rails
  :ensure t)
(projectile-rails-global-mode)
(define-key projectile-rails-mode-map (kbd "C-c e") 'projectile-rails-command-map)
#+END_SRC

#+RESULTS:
: projectile-rails-command-map

* web-mode

web-mode ensures syntax highlighting for a bunch of web code files (html), including .html.erb

#+BEGIN_SRC emacs-lisp
(use-package web-mode
  :ensure t
  :mode
  ("\\.ejs\\'" "\\.hbs\\'" "\\.html\\'" "\\.php\\'" "\\.[jt]sx?\\'")
  :config
  (setq web-mode-content-types-alist '(("jsx" . "\\.[jt]sx?\\'")))
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-script-padding 2)
  (setq web-mode-block-padding 2)
  (setq web-mode-style-padding 2)
  (setq web-mode-enable-auto-pairing t)
  (setq web-mode-enable-auto-closing t)
  (setq web-mode-enable-current-element-highlight t))

(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
#+END_SRC

#+RESULTS:
: ((\.jsx?$ . web-mode) (\.djhtml\' . web-mode) (\.mustache\' . web-mode) (\.erb\' . web-mode) (\.as[cp]x\' . web-mode) (\.[agj]sp\' . web-mode) (\.tpl\.php\' . web-mode) (\.phtml\' . web-mode) (\.odc\' . archive-mode) (\.odf\' . archive-mode) (\.odi\' . archive-mode) (\.otp\' . archive-mode) (\.odp\' . archive-mode) (\.otg\' . archive-mode) (\.odg\' . archive-mode) (\.ots\' . archive-mode) (\.ods\' . archive-mode) (\.odm\' . archive-mode) (\.ott\' . archive-mode) (\.odt\' . archive-mode) (\.[jt]sx?\' . web-mode) (\.php\' . web-mode) (\.html\' . web-mode) (\.hbs\' . web-mode) (\.ejs\' . web-mode) (/Pipfile.lock$ . js2-mode) (/Pipfile$ . conf-mode) (\.xsh$ . python-mode) (\.ipynb$ . js2-mode) (\.py\' . python-mode) (/Users/jeroen/Documents/journal/\(?1:[0-9]\{4\}\)\(?2:[0-9][0-9]\)\(?3:[0-9][0-9]\)\(\.gpg\)?\' . org-journal-mode) (\.gpg\(~\|\.~[0-9]+~\)?\' nil epa-file) (\.hva\' . latex-mode) (\.drv\' . latex-mode) (/git-rebase-todo\' . git-rebase-mode) (\.\(?:md\|markdown\|mkd\|mdown\|mkdn\|mdwn\)\' . markdown-mode) (/nginx/.+\.conf\' . nginx-mode) (nginx\.conf\' . nginx-mode) (/PKGBUILD\' . pkgbuild-mode) (\.toml\' . toml-mode) (\.ts$ . typescript-mode) (\.\(e?ya?\|ra\)ml\' . yaml-mode) (\.elc\' . elisp-byte-code-mode) (\.zst\' nil jka-compr) (\.dz\' nil jka-compr) (\.xz\' nil jka-compr) (\.lzma\' nil jka-compr) (\.lz\' nil jka-compr) (\.g?z\' nil jka-compr) (\.bz2\' nil jka-compr) (\.Z\' nil jka-compr) (\.vr[hi]?\' . vera-mode) (\(?:\.\(?:rbw?\|ru\|rake\|thor\|jbuilder\|rabl\|gemspec\|podspec\)\|/\(?:Gem\|Rake\|Cap\|Thor\|Puppet\|Berks\|Vagrant\|Guard\|Pod\)file\)\' . ruby-mode) (\.re?st\' . rst-mode) (\.py[iw]?\' . python-mode) (\.m\' . octave-maybe-mode) (\.less\' . less-css-mode) (\.scss\' . scss-mode) (\.awk\' . awk-mode) (\.\(u?lpc\|pike\|pmod\(\.in\)?\)\' . pike-mode) (\.idl\' . idl-mode) (\.java\' . java-mode) (\.m\' . objc-mode) (\.ii\' . c++-mode) (\.i\' . c-mode) (\.lex\' . c-mode) (\.y\(acc\)?\' . c-mode) (\.h\' . c-or-c++-mode) (\.c\' . c-mode) (\.\(CC?\|HH?\)\' . c++-mode) (\.[ch]\(pp\|xx\|\+\+\)\' . c++-mode) (\.\(cc\|hh\)\' . c++-mode) (\.\(bat\|cmd\)\' . bat-mode) (\.[sx]?html?\(\.[a-zA-Z_]+\)?\' . mhtml-mode) (\.svgz?\' . image-mode) (\.svgz?\' . xml-mode) (\.x[bp]m\' . image-mode) (\.x[bp]m\' . c-mode) (\.p[bpgn]m\' . image-mode) (\.tiff?\' . image-mode) (\.gif\' . image-mode) (\.png\' . image-mode) (\.jpe?g\' . image-mode) (\.te?xt\' . text-mode) (\.[tT]e[xX]\' . tex-mode) (\.ins\' . tex-mode) (\.ltx\' . latex-mode) (\.dtx\' . doctex-mode) (\.org\' . org-mode) (\.el\' . emacs-lisp-mode) (Project\.ede\' . emacs-lisp-mode) (\.\(scm\|stk\|ss\|sch\)\' . scheme-mode) (\.l\' . lisp-mode) (\.li?sp\' . lisp-mode) (\.[fF]\' . fortran-mode) (\.for\' . fortran-mode) (\.p\' . pascal-mode) (\.pas\' . pascal-mode) (\.\(dpr\|DPR\)\' . delphi-mode) (\.ad[abs]\' . ada-mode) (\.ad[bs]\.dg\' . ada-mode) (\.\([pP]\([Llm]\|erl\|od\)\|al\)\' . perl-mode) (Imakefile\' . makefile-imake-mode) (Makeppfile\(?:\.mk\)?\' . makefile-makepp-mode) (\.makepp\' . makefile-makepp-mode) (\.mk\' . makefile-bsdmake-mode) (\.make\' . makefile-bsdmake-mode) (GNUmakefile\' . makefile-gmake-mode) ([Mm]akefile\' . makefile-bsdmake-mode) (\.am\' . makefile-automake-mode) (\.texinfo\' . texinfo-mode) (\.te?xi\' . texinfo-mode) (\.[sS]\' . asm-mode) (\.asm\' . asm-mode) (\.css\' . css-mode) (\.mixal\' . mixal-mode) (\.gcov\' . compilation-mode) (/\.[a-z0-9-]*gdbinit . gdb-script-mode) (-gdb\.gdb . gdb-script-mode) ([cC]hange\.?[lL]og?\' . change-log-mode) ([cC]hange[lL]og[-.][0-9]+\' . change-log-mode) (\$CHANGE_LOG\$\.TXT . change-log-mode) (\.scm\.[0-9]*\' . scheme-mode) (\.[ckz]?sh\'\|\.shar\'\|/\.z?profile\' . sh-mode) (\.bash\' . sh-mode) (\(/\|\`\)\.\(bash_\(profile\|history\|log\(in\|out\)\)\|z?log\(in\|out\)\)\' . sh-mode) (\(/\|\`\)\.\(shrc\|zshrc\|m?kshrc\|bashrc\|t?cshrc\|esrc\)\' . sh-mode) (\(/\|\`\)\.\([kz]shenv\|xinitrc\|startxrc\|xsession\)\' . sh-mode) (\.m?spec\' . sh-mode) (\.m[mes]\' . nroff-mode) (\.man\' . nroff-mode) (\.sty\' . latex-mode) (\.cl[so]\' . latex-mode) (\.bbl\' . latex-mode) (\.bib\' . bibtex-mode) (\.bst\' . bibtex-style-mode) (\.sql\' . sql-mode) (\(acinclude\|aclocal\|acsite\)\.m4\' . autoconf-mode) (\.m[4c]\' . m4-mode) (\.mf\' . metafont-mode) (\.mp\' . metapost-mode) (\.vhdl?\' . vhdl-mode) (\.article\' . text-mode) (\.letter\' . text-mode) (\.i?tcl\' . tcl-mode) (\.exp\' . tcl-mode) (\.itk\' . tcl-mode) (\.icn\' . icon-mode) (\.sim\' . simula-mode) (\.mss\' . scribe-mode) (\.f9[05]\' . f90-mode) (\.f0[38]\' . f90-mode) (\.indent\.pro\' . fundamental-mode) (\.\(pro\|PRO\)\' . idlwave-mode) (\.srt\' . srecode-template-mode) (\.prolog\' . prolog-mode) (\.tar\' . tar-mode) (\.\(arc\|zip\|lzh\|lha\|zoo\|[jew]ar\|xpi\|rar\|cbr\|7z\|ARC\|ZIP\|LZH\|LHA\|ZOO\|[JEW]AR\|XPI\|RAR\|CBR\|7Z\)\' . archive-mode) (\.oxt\' . archive-mode) (\.\(deb\|[oi]pk\)\' . archive-mode) (\`/tmp/Re . text-mode) (/Message[0-9]*\' . text-mode) (\`/tmp/fol/ . text-mode) (\.oak\' . scheme-mode) (\.sgml?\' . sgml-mode) (\.x[ms]l\' . xml-mode) (\.dbk\' . xml-mode) (\.dtd\' . sgml-mode) (\.ds\(ss\)?l\' . dsssl-mode) (\.js[mx]?\' . javascript-mode) (\.har\' . javascript-mode) (\.json\' . javascript-mode) (\.[ds]?va?h?\' . verilog-mode) (\.by\' . bovine-grammar-mode) (\.wy\' . wisent-grammar-mode) ([:/\]\..*\(emacs\|gnus\|viper\)\' . emacs-lisp-mode) (\`\..*emacs\' . emacs-lisp-mode) ([:/]_emacs\' . emacs-lisp-mode) (/crontab\.X*[0-9]+\' . shell-script-mode) (\.ml\' . lisp-mode) (\.ld[si]?\' . ld-script-mode) (ld\.?script\' . ld-script-mode) (\.xs\' . c-mode) (\.x[abdsru]?[cnw]?\' . ld-script-mode) (\.zone\' . dns-mode) (\.soa\' . dns-mode) (\.asd\' . lisp-mode) (\.\(asn\|mib\|smi\)\' . snmp-mode) (\.\(as\|mi\|sm\)2\' . snmpv2-mode) (\.\(diffs?\|patch\|rej\)\' . diff-mode) (\.\(dif\|pat\)\' . diff-mode) (\.[eE]?[pP][sS]\' . ps-mode) (\.\(?:PDF\|DVI\|OD[FGPST]\|DOCX\|XLSX?\|PPTX?\|pdf\|djvu\|dvi\|od[fgpst]\|docx\|xlsx?\|pptx?\)\' . doc-view-mode-maybe) (configure\.\(ac\|in\)\' . autoconf-mode) (\.s\(v\|iv\|ieve\)\' . sieve-mode) (BROWSE\' . ebrowse-tree-mode) (\.ebrowse\' . ebrowse-tree-mode) (#\*mail\* . mail-mode) (\.g\' . antlr-mode) (\.mod\' . m2-mode) (\.ses\' . ses-mode) (\.docbook\' . sgml-mode) (\.com\' . dcl-mode) (/config\.\(?:bat\|log\)\' . fundamental-mode) (/\.\(authinfo\|netrc\)\' . authinfo-mode) (\.\(?:[iI][nN][iI]\|[lL][sS][tT]\|[rR][eE][gG]\|[sS][yY][sS]\)\' . conf-mode) (\.la\' . conf-unix-mode) (\.ppd\' . conf-ppd-mode) (java.+\.conf\' . conf-javaprop-mode) (\.properties\(?:\.[a-zA-Z0-9._-]+\)?\' . conf-javaprop-mode) (\.toml\' . conf-toml-mode) (\.desktop\' . conf-desktop-mode) (/\.redshift\.conf\' . conf-windows-mode) (\`/etc/\(?:DIR_COLORS\|ethers\|.?fstab\|.*hosts\|lesskey\|login\.?de\(?:fs\|vperm\)\|magic\|mtab\|pam\.d/.*\|permissions\(?:\.d/.+\)?\|protocols\|rpc\|services\)\' . conf-space-mode) (\`/etc/\(?:acpid?/.+\|aliases\(?:\.d/.+\)?\|default/.+\|group-?\|hosts\..+\|inittab\|ksysguarddrc\|opera6rc\|passwd-?\|shadow-?\|sysconfig/.+\)\' . conf-mode) ([cC]hange[lL]og[-.][-0-9a-z]+\' . change-log-mode) (/\.?\(?:gitconfig\|gnokiirc\|hgrc\|kde.*rc\|mime\.types\|wgetrc\)\' . conf-mode) (/\.\(?:asound\|enigma\|fetchmail\|gltron\|gtk\|hxplayer\|mairix\|mbsync\|msmtp\|net\|neverball\|nvidia-settings-\|offlineimap\|qt/.+\|realplayer\|reportbug\|rtorrent\.\|screen\|scummvm\|sversion\|sylpheed/.+\|xmp\)rc\' . conf-mode) (/\.\(?:gdbtkinit\|grip\|mpdconf\|notmuch-config\|orbital/.+txt\|rhosts\|tuxracer/options\)\' . conf-mode) (/\.?X\(?:default\|resource\|re\)s\> . conf-xdefaults-mode) (/X11.+app-defaults/\|\.ad\' . conf-xdefaults-mode) (/X11.+locale/.+/Compose\' . conf-colon-mode) (/X11.+locale/compose\.dir\' . conf-javaprop-mode) (\.~?[0-9]+\.[0-9][-.0-9]*~?\' nil t) (\.\(?:orig\|in\|[bB][aA][kK]\)\' nil t) ([/.]c\(?:on\)?f\(?:i?g\)?\(?:\.[a-zA-Z0-9._-]+\)?\' . conf-mode-maybe) (\.[1-9]\' . nroff-mode) (\.art\' . image-mode) (\.avs\' . image-mode) (\.bmp\' . image-mode) (\.cmyk\' . image-mode) (\.cmyka\' . image-mode) (\.crw\' . image-mode) (\.dcr\' . image-mode) (\.dcx\' . image-mode) (\.dng\' . image-mode) (\.dpx\' . image-mode) (\.fax\' . image-mode) (\.hrz\' . image-mode) (\.icb\' . image-mode) (\.icc\' . image-mode) (\.icm\' . image-mode) (\.ico\' . image-mode) (\.icon\' . image-mode) (\.jbg\' . image-mode) (\.jbig\' . image-mode) (\.jng\' . image-mode) (\.jnx\' . image-mode) (\.miff\' . image-mode) (\.mng\' . image-mode) (\.mvg\' . image-mode) (\.otb\' . image-mode) (\.p7\' . image-mode) (\.pcx\' . image-mode) (\.pdb\' . image-mode) (\.pfa\' . image-mode) (\.pfb\' . image-mode) (\.picon\' . image-mode) (\.pict\' . image-mode) (\.rgb\' . image-mode) (\.rgba\' . image-mode) (\.tga\' . image-mode) (\.wbmp\' . image-mode) (\.webp\' . image-mode) (\.wmf\' . image-mode) (\.wpg\' . image-mode) (\.xcf\' . image-mode) (\.xmp\' . image-mode) (\.xwd\' . image-mode) (\.yuv\' . image-mode) (\.tgz\' . tar-mode) (\.tbz2?\' . tar-mode) (\.txz\' . tar-mode) (\.tzst\' . tar-mode))
* react

i use a number of packages here: first, web-mode, which does a bunch of stuff. initialization:

#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.jsx?$" . web-mode)) ;; auto-enable for .js/.jsx files
(setq web-mode-content-types-alist '(("jsx" . "\\.js[x]?\\'")))

(defun web-mode-init-hook ()
  "Hooks for Web mode.  Adjust indent."
  (setq web-mode-markup-indent-offset 2))

(add-hook 'web-mode-hook  'web-mode-init-hook)
#+END_SRC

#+RESULTS:
| web-mode-init-prettier-hook | web-mode-init-hook | my/activate-tide-mode | prettier-js-mode |

second package: prettier-js, which autoformats js files on save. for this, i also install
add-node-modules-path

#+BEGIN_SRC emacs-lisp
(setq prettier-js-args (list "--no-semi" "--single-quote"))

(defun web-mode-init-prettier-hook ()
  (add-node-modules-path)
  (prettier-js-mode))

(add-hook 'web-mode-hook  'web-mode-init-prettier-hook)
#+END_SRC

#+RESULTS:
| web-mode-init-prettier-hook | web-mode-init-hook | my/activate-tide-mode | prettier-js-mode |

then, flymake-eslint, which does eslint:

#+BEGIN_SRC emacs-lisp
;; (defcustom flymake-eslint-executable-name "eslint"
;;   "Name of executable to run when checker is called.  Must be present in variable `exec-path'."
;;   :type 'string
;;   :group 'flymake-eslint)

;; (add-hook 'web-mode-hook
;;   (lambda ()
;;     (flymake-eslint-enable)))
#+END_SRC

#+RESULTS:

* canvas-utils
#+BEGIN_SRC emacs-lisp
;; (add-to-list 'load-path "~/code/paulodder/canvas-utils/")
;; (require 'canvas-utils)
;; (setq canvas-baseurl "https://canvas.uva.nl") ; url you visit to go to the
                                        ; canvas instance of your institution
                                        ; (e.g. https://canvas.uva.nl)
;; (setq canvas-token "10392~0HN7MJHY2C0MA2XcZlNvra3OScZR8crUs7xxbjT6yl6rb1YEPYYgb9yzlSgdTETW") ; when logged in generate an access
                                        ; token under Account > Settings
                                        ; > Approved integrations
#+END_SRC

#+RESULTS:
* tramp

make sure tramp works on windows:

#+BEGIN_SRC emacs-lisp
(when (eq window-system 'w32)
  (setq putty-directory "C:/Program Files/PuTTY")
  (setq tramp-default-method "plink")
  (when (and (not (string-match putty-directory (getenv "PATH")))
       (file-directory-p putty-directory))
    (setenv "PATH" (concat putty-directory ";" (getenv "PATH")))
    (add-to-list 'exec-path putty-directory)))
#+END_SRC

#+RESULTS:

* tramp-virtualenv

#+BEGIN_SRC emacs-lisp
(load-file "~/code/matthewlmcclure/tramp-virtualenv/tramp-virtualenv.el")
#+END_SRC

#+RESULTS:
: t
* keybase

run: =git clone https://github.com/paulodder/keybase-chat=

#+BEGIN_SRC emacs-lisp
(setq my-keybase-username "jpj8")
(use-package keybase-chat
  :straight (keybase-chat
             :host github
             :repo "paulodder/keybase-chat"
             )
)

(bind-key (kbd "C-c k") 'keybase-join-channel)
#+END_SRC

#+RESULTS:
: keybase-join-channel

* avy
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-;") 'avy-goto-char-2)
#+END_SRC

#+RESULTS:
: avy-goto-char-2
* org-mode

Change the size of inline latex eqs (=C-x C-c C-l=).

#+BEGIN_SRC emacs-lisp
(plist-put org-format-latex-options :scale 1.8)
#+END_SRC

#+RESULTS:
| :foreground | default | :background | default | :scale | 1.8 | :html-foreground | Black | :html-background | Transparent | :html-scale | 1.0 | :matchers | (begin $1 $ $$ \( \[) |

In order to create those images when opening org file, insert this:
=#+STARTUP: latexpreview=.

** toggle code block execution

#+BEGIN_SRC emacs-lisp
(defun org-toggle-execution-on-export ()
  (interactive)
  (setq org-export-babel-evaluate (not org-export-babel-evaluate))
  (message "org-export-babel-evaluate turned %s" (if org-export-babel-evaluate "on" "off")))
#+END_SRC

#+RESULTS:
: org-toggle-execution-on-export

** [paul] execute source block

Let's write a function that executes a command in the corresponding shell
without having the whole file freeze. Instead, we copy the current code block's
buffer content and paste it in the shell, and then execute the command.


#+BEGIN_SRC emacs-lisp
(defun org-execute-code-in-shell  (&optional arg _info)
  "Copy current src block's contents and execute it in code shell buffer."
  (interactive)
  (save-window-excursion
    (org-babel-switch-to-session arg (org-babel-get-src-block-info))
    (end-of-buffer)
    (yank)
    (comint-send-input)
    (comint-send-input)
    (comint-send-input)
    ))

(defun org-execute-code-in-shell  (&optional arg _info)
  "Copy current src block's contents and execute it in code shell buffer."
  (interactive "P")
  (let ((this-window (selected-window))
        (info (org-babel-get-src-block-info)))
    (org-babel-switch-to-session arg info)
    (end-of-buffer)
    (yank)
    (comint-send-input)
    (comint-send-input)
    (comint-send-input)
    (select-window this-window)
    ))
#+END_SRC

#+RESULTS:
: org-execute-code-in-shell

Let's make =C-c C-c= execute the =execute-code-in-shell= function, and let =C-c
c= execute the regular =org-ctrl-c-ctrl-c= function.
#+BEGIN_SRC emacs-lisp
(org-defkey org-mode-map "\C-c\C-c" `org-execute-code-in-shell)
(org-defkey org-mode-map "\C-c\c" 'org-ctrl-c-ctrl-c)
#+END_SRC

#+RESULTS:
: org-ctrl-c-ctrl-c

** copy src block

#+BEGIN_SRC emacs-lisp
(fset 'org-copy-src-block
   (kmacro-lambda-form [?\C-c ?\' ?\C-x ?h ?\M-w ?\C-u ?\C-  ?\C-u ?\C-  ?\C-c ?\'] 0 "%d"))


(define-key org-mode-map (kbd "C-M-w") 'org-copy-src-block)
#+END_SRC

#+RESULTS:
: org-copy-src-block

** edit random comments and strings with org-mode

If you wanna edit some large comment (e.g. docstring) using org-mode editing
ease, use this:

#+BEGIN_SRC emacs-lisp
(use-package poporg
      :bind (("C-c /" . poporg-dwim)))
#+END_SRC

#+RESULTS:
: poporg-dwim

** org to ipynb

#+BEGIN_SRC emacs-lisp
;; (add-to-list 'load-path "~/.emacs.d/github/ox-ipynb")
;; (require 'ox-ipynb)
#+END_SRC

#+RESULTS:
** paul stuff
*** auto-indentation
Setting this variable causes auto-indentation inside org-mode src blocks
#+BEGIN_SRC emacs-lisp
(setq org-src-tab-acts-natively t
      org-src-preserve-indentation nil
      org-edit-src-content-indentation 0)
#+END_SRC

#+RESULTS:
: 0

#+BEGIN_SRC emacs-lisp

(load-library "org")
(push "/home/paul/org-mode/lisp" load-path)
(define-key org-mode-map (kbd "C-c o") 'org-open-at-point)
(define-key global-map (kbd "C-C l") 'org-store-link)

(setq org-todo-keyword-faces
      '(("TODO" . org-warning) ("WIP" . "yellow")
        ("CANCELED" . (:foreground "blue" :weight bold))
        ("DONE" . "green")))
(use-package org-bullets
  ;; :hook (org-mode org-bullets-mode)
  :init (progn
          (setq org-ellipsis "⤵")
          ;; (add-hook org-mode-hook org-bullets-mode)
          ))

(add-hook `org-mode-hook (lambda () (setq inhibit-read-only 1)
                           ;; (auto-insert-mode)
                           (wrap-region-add-wrapper "=" "=")
                           (wrap-region-add-wrapper "~" "~")
                           (wrap-region-add-wrapper "+" "+")
                           (wrap-region-add-wrapper "/" "/")
                           (wrap-region-add-wrapper "*" "*")
                           (wrap-region-add-wrapper "_" "_")
                           (wrap-region-add-wrapper "|" "|")
                           ;; (modify-syntax-entry ?= "\"")
                           (modify-syntax-entry ?* "\"")
                           ;; (modify-syntax-entry ?_ "\"")
                           (modify-syntax-entry ?| "\"")
                           (org-bullets-mode)
                           ))

;; (defadvice syntax-table (before in-src activate)
;;   (if (org-in-src-block-p)
;;       (message "HEERE")
;;     (setq-local syntax-table python-mode-syntax-table)
;;     (setq-local syntax-table (syntax-table))))

;; (define-key org-mode-map "\C-\M-f" '(lambda ()
;;                                      (interactive)
;;                                      (if (org-in-src-block-p)
;;                                          (with-syntax-table
;;                                              python-mode-syntax-table
;;                                            (forward-sexp))
;;                                        (forward-sexp)
;;                                            )))

;; (setq prettify-symbols-alist
;; (prettify-utils-generate (("\\mathbb{N}" "ℕ"))))
;; (add-hook `org-mode-hook (lambda ()
;; (setq prettify-symbols-alist '(("\\models" .  "⊧") ("\\vdash" .  "⊢")
;;                                ("\\bar{a}"  . "a̅") ("\\underbrace"  . "a⃗")
;;                                ("\\subseteq"  . "⊆")))
;; (prettify-symbols-mode)))
;; (add-hook 'global-prettify-symbols-mode (lambda ()
;; (setq prettify-symbols-alist '(("\\models" .  "⊧") ("\\vdash" .  "⊢")
;; ("\\bar{a}"  . "a̅") ("\\underbrace"  . "a⃗")
;; ("\\subseteq"  . "⊆")))

;; ))
;; (add-hook 'org-mode-hook (org-bullets-mode))

;; (add-hook 'org-mode-hook org-bullets-mode)


;; Org babel languages
(org-babel-do-load-languages
 'org-babel-load-languages
 (mapcar (lambda (m) (cons m t))
         '(;; C calc dot
           emacs-lisp ;; gnuplot java js latex
           ;; lisp
           python ipython
           latex
           ;; R racket  not necessary for my purposes
           ;; ruby scheme
           shell sqlite ;; haskell
           sql)))
(defun my-org-confirm-babel-evaluate (lang body)
  (not (member lang '("ipython" "python" "emacs-lisp" "sh"))))

(setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
;; (use-package ox-latex
;;   :config (push '(racket "Racket") org-latex-listings-langs))

;; (push '("https" . "i.reddituploads.com") org-html-inline-image-rules)
;;   (require 'ob-ipython)
;; (use-package ob-ipython :ensure t)
(require 'package)
;; (add-to-list 'package-archives
;;                  '("melpa" . "https://melpa.org/packages/"))
#+END_SRC

#+RESULTS:
: package

#+RESULTS:
*** syntax table stuff
Let's make sure that syntax table inside src blocks matches the one used for
that language
#+BEGIN_SRC emacs-lisp
(defun org--get-syntax-table-for-src () (interactive)
       (let* ((lang (first (org-babel-get-src-block-info)))
              )
       (cond ((string-equal "emacs-lisp" lang)
              emacs-lisp-mode-syntax-table))
))

#+END_SRC

#+RESULTS:
: org--get-syntax-table-for-src

*** Sql mode related

#+BEGIN_SRC emacs-lisp
;; (package-initialize)
;;   (require 'ob-sql-mode)
#+END_SRC

#+RESULTS:

Code beautifier (see https://www.emacswiki.org/emacs/SqlBeautify)
#+BEGIN_SRC emacs-lisp
(defun sql-beautify-region (beg end)
  "Beautify SQL in region between beg and END."
  (interactive "r")
  (save-excursion
    (shell-command-on-region beg end "anbt-sql-formatter" nil t)))
    ;; change sqlbeautify to anbt-sql-formatter if you
    ;;ended up using the ruby gem

(defun sql-beautify-buffer ()
 "Beautify SQL in buffer."
 (interactive)
 (sql-beautify-region (point-min) (point-max)))

(define-advice org-edit-src-exit (:before (&rest _args) format-sql)
  "Run `blacken-buffer' when leaving an org-mode Python source block."
  (when (eq major-mode 'sql-mode)
    (sql-beautify-buffer)))

#+END_SRC

#+RESULTS:
: org-edit-src-exit@format-sql

This is to remove the angle brackets from time stamps exported to html and tex.
Look into more information on beautification [[https://stackoverflow.com/a/33716338/3414663][here]]

#+BEGIN_SRC emacs-lisp
(defun org-export-filter-timestamp-remove-brackets (timestamp backend info)
  "removes relevant brackets from a timestamp"
  (cond
   ((org-export-derived-backend-p backend 'latex)
    (replace-regexp-in-string "[<>]\\|[][]" "" timestamp))
   ((org-export-derived-backend-p backend 'html)
    (replace-regexp-in-string "&[lg]t;\\|[][]" "" timestamp))))

(eval-after-load 'ox '(add-to-list
                       'org-export-filter-timestamp-functions
                       'org-export-filter-timestamp-remove-brackets))
#+END_SRC

#+RESULTS:
| org-export-filter-timestamp-remove-brackets |

*** LaTeX macros
This [[   https://www.reddit.com/r/orgmode/comments/7u2n0h/tip_for_defining_latex_macros_for_use_in_both/][idea]] is to make a new org language called latex-macros which allows math
to be exported both to HTML and to LaTeX.

Usage:
#+BEGIN_EXAMPLE
  #+BEGIN_SRC latex-macros
  \newcommand{\Z}{\mathbb{Z}}
  \newcommand{\Hom}{\mathrm{Hom}}
  #+END_SRC
#+END_EXAMPLE

#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-src-lang-modes '("latex-macros" . latex))

  (defvar org-babel-default-header-args:latex-macros
    '((:results . "raw")
      (:exports . "results")))

  (defun prefix-all-lines (pre body)
    (with-temp-buffer
      (insert body)
      (string-insert-rectangle (point-min) (point-max) pre)
      (buffer-string)))

  (defun org-babel-execute:latex-macros (body _params)
    (concat
     (prefix-all-lines "#+LATEX_HEADER: " body)
     "\n#+HTML_HEAD_EXTRA: <div style=\"display: none\"> \\(\n"
     (prefix-all-lines "#+HTML_HEAD_EXTRA: " body)
     "\n#+HTML_HEAD_EXTRA: \\)</div>\n"))
#+END_SRC

#+RESULTS:
: org-babel-execute:latex-macros
*** venv functions
To use virtualenv python (needed for keras), you can use
https://emacs.stackexchange.com/questions/24453/weird-shell-output-when-using-ipython-5
https://github.com/jorgenschaefer/elpy/issues/992#issuecomment-249165923
#+BEGIN_SRC emacs-lisp
(setenv "IPY_TEST_SIMPLE_PROMPT" "1")
;; (setq python-shell-interpreter "ipython"
;;       python-shell-interpreter-args "--simple-prompt -i --colors=Linux --profile=default")
;; python-shell-interpreter-args "--simple-prompt -i")
;; "--colors=Linux --profile=default"
(setq org-babel-python-command "ipython")
(defun org-py3.6 ()
  (interactive)
  ;; (setq python-shell-virtualenv-root
  (setq org-babel-python-command "python3.6"))
;; (concat default-directory "~/.envs/py3.6")))
(defun org-quanti ()
  (interactive)
  ;; (setq python-shell-virtualenv-root
  (setq org-babel-python-command "/home/paul/.virtualenvs/quanti/bin/python"))
;; (concat default-directory "~/.envs/py3.6"))
(defun org-nhbc-poc ()
  (interactive)
  (setq org-babel-python-command "/home/paul/.virtualenvs/nhbc-poc/bin/python"))

(defun org-ogi_products ()
  (interactive)
  (setq org-babel-python-command "/home/paul/.virtualenvs/ogi_products/bin/python")
  (setq python-shell-interpreter "/home/paul/.virtualenvs/ogi_products/bin/ipython"))

(defun org-ogi-db ()
  (interactive)
  ;; (setq python-shell-virtualenv-root
  (setq org-babel-python-command "/home/paul/.virtualenvs/ogi-database/bin/python"))

(defun org-ogi-quotes ()
  (interactive)
  ;; (setq python-shell-virtualenv-root
  (setq org-babel-python-command "/home/paul/.virtualenvs/ogi-quotes/bin/python"))

(defun org-local-py3.7 ()
  (interactive)
  ;; (setq python-shell-virtualenv-root
  (setq org-babel-python-command "/usr/bin/python3.7"))
;; (concat default-directory "~/.envs/py3.6")))



(defun py-nhbc-poc ()
  (interactive)
  ;; (setq python-shell-virtualenv-root
  (setq python-shell-interpreter "/home/paul/.virtualenvs/nhbc-poc/bin/python"))
;; (concat default-directory "~/.envs/py3.6")))


#+END_SRC

#+RESULTS:
: py-nhbc-poc
*** optimizing
Let's try to write a function that takes python code buffer and appends it to
the shell, instead of executing it and having to wait for it to finish.

#+BEGIN_SRC emacs-lisp
  (defun execute-in-shell (&optional arg _info)
    "Switch to code buffer and display sessiona and execute code there."
    (interactive "P")
    (let ((swap-windows
           (lambda ()
             (let ((other-window-buffer (window-buffer (next-window))))
               (set-window-buffer (next-window) (current-buffer))
               (set-window-buffer (selected-window) other-window-buffer))
             (other-window 1)))
          (info (org-babel-get-src-block-info))
          (org-src-window-setup 'reorganize-frame))
      (save-window-excursion
        (org-babel-switch-to-session arg info))
        (org-edit-src-code)
        (copy-to-buffer  (point-min) (point-max))
        (funcall swap-windows)
        (org-edit-src-exit)
      ))

;; (require 'ob-async)
#+END_SRC

#+RESULTS:
: execute-in-shell
*** pygments
#+BEGIN_SRC emacs-lisp
(require 'ox-latex)
(add-to-list 'org-latex-packages-alist '("" "minted"))
(setq org-latex-listings 'minted)

(setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))

(setq org-src-fontify-natively t)

;; (org-babel-do-load-languages
;;  'org-babel-load-languages
;;  '((R . t)
;;    (latex . t)))

#+END_SRC

#+RESULTS:
: t
*** exporting
#+BEGIN_SRC emacs-lisp
(setq org-latex-inline-image-rules '(("file" . "\\.\\(pdf\\|jpeg\\|jpg\\|png\\|ps\\|eps\\|tikz\\|pgf\\|svg\\|gif\\)\\'")))
#+END_SRC

#+RESULTS:
: ((file . \.\(pdf\|jpeg\|jpg\|png\|ps\|eps\|tikz\|pgf\|svg\|gif\)\'))

* latex
#+BEGIN_SRC emacs-lisp
;; (require 'auctex)
(require 'mode-local)
  (use-package auctex
    :defer t
    :ensure t
    :hook (LaTeX-mode-hook .
    electric-quote-local-mode)
    :config
    ;; Some LaTeX packages need to run a shell command, e.g. minted needs
    ;; pygmentize
    (push '("LaTeX-shell"
            "%`%l -shell-escape %(mode)%' %t"
            TeX-run-TeX
            nil
            (latex-mode doctex-mode)
            :help "Run LaTeX allowing shell escape")
          TeX-command-list)
    (setq font-latex-fontify-script nil)
    (setq-mode-local latex-mode region-extract-function latex--region-extract-function)
    )


  ;; configs below need to be outside the use-package since org-mode may need
  ;; them directly.

  (setq TeX-view-program-list
        '(("mupdf" "/bin/mupdf %s.pdf"))
        TeX-view-program-selection
        '((output-pdf "PDF Tools")
          ;; (output-pdf "mupdf")
          ((output-dvi style-pstricks) "dvips and gv")
          (output-dvi "xdvi")
          (output-html "xdg-open"))
        TeX-source-correlate-start-server t
        LaTeX-electric-left-right-brace t)

  (setq bibtex-completion-bibliography
        (mapcar (lambda (f)
                  (concat
                   "/path/to/media/data/tie/path/to/media/writing/bib/"
                   f
                   ".bib"))
                '("bon" "counting" "dsls" "etc")))

  ;; Update PDF buffers after successful LaTeX runs
  (add-hook 'TeX-after-compilation-finished-functions
            #'TeX-revert-document-buffer)

#+END_SRC

#+RESULTS:
| TeX-revert-document-buffer |

Does not work yet for
+ end of lines
+ copied math parts that were already delimited by $'s
#+BEGIN_SRC emacs-lisp
(defun has-face-at (pos face-in-question &optional object)
  (let ((face-result-at-pos (get-text-property pos 'face object)))
    (if (eq (type-of face-result-at-pos) 'cons)
        (seq-contains face-result-at-pos face-in-question)
      (eq face-result-at-pos face-in-question))
    ))
;; (face-at-post ))


(defun latex--add-math-delimiters (substr)
  "add $ if necessary"
  (if (<= (length substr) 1)
      substr
    ;; (message (format "%s" (has-face-at  0 'font-latex-math-face substr)))
    (let*
        (;; (face-result-at-start (get-text-property 0 'face substr))
         ;; (face-at-start (if (eq (type-of face-result-at-start) 'cons) (first face-result-at-start) face-result-at-start))
         (substr-prefixed (if (and (not (string-prefix-p "$" substr))
                                   (has-face-at  0 'font-latex-math-face substr)
                                   )
                              (concat "$" substr)
                            substr))
         (substr-suffixed
          (if (and (not (string-suffix-p "$" substr-prefixed))
                   ;; (has-face-at  (- (length substr-prefixed) 1) 'font-latex-math-face substr-prefixed)
                   (has-face-at (- (length substr-prefixed) 1)
                   ;; (has-face-at (length substr-prefixed)
                                'font-latex-math-face substr-prefixed)
                   )
              (concat  substr-prefixed "$")
            substr-prefixed))
         )
      substr-suffixed

      )

    )
  )


;; (defun latex--add-math-delimiters (str)
;;   (let ((max-pos (length str)))
;;     (message "AAA")
;;     str
;; ))

(defvar latex--region-extract-function
  (lambda (method)
    (when (region-beginning)
      (cond
       ((eq method 'bounds)
        (list (cons (region-beginning) (region-end))))
       ((eq method 'delete-only)
        (delete-region (region-beginning) (region-end)))
       (t
        (latex--add-math-delimiters (filter-buffer-substring (region-beginning) (region-end) method))
        ;; (message out)
        ;; (message (latex--add-math-delimiters out))
        ))))
  "Function to get the region's content.
Called with one argument METHOD which can be:
- nil: return the content as a string (list of strings for
  non-contiguous regions).
- `delete-only': delete the region; the return value is undefined.
- `bounds': return the boundaries of the region as a list of one
  or more cons cells of the form (START . END).
- anything else: delete the region and return its content
  as a string (or list of strings for non-contiguous regions),
  after filtering it with `filter-buffer-substring', which
c  is called, for each contiguous sub-region, with METHOD as its
  3rd argument.")
(setq-mode-local latex-mode region-extract-function latex--region-extract-function)
#+END_SRC

#+RESULTS:
| lambda | (method) | (if (region-beginning) (progn (cond ((eq method (quote bounds)) (list (cons (region-beginning) (region-end)))) ((eq method (quote delete-only)) (delete-region (region-beginning) (region-end))) (t (latex--add-math-delimiters (filter-buffer-substring (region-beginning) (region-end) method)))))) |

Now let's also write a function that removes $'s if it's being copied inside a
math mode already. We need to adapt the =yank-handled-properties= variable
#+BEGIN_SRC emacs-lisp
(defun has-face (face-in-question face-seq)
  )

(defun latex--possibly-remove-math-delimiters (face start end)
  ;; (message (format "%s" (seq-contains face 'font-latex-math-face)))
  ;; (message (format "%s" (get-text-property (+ start 1) :foreground)))
  (let* ((substr (buffer-substring start end))
         ;; (face-after (get-text-property (+ end 1) 'face ))
         ;; (face-before (get-text-property (- start 1) 'face ))
         (has-face-after (has-face-at (+ end 1) 'font-latex-math-face);; (get-text-property (+ end 1) 'face )
                         )
         (has-face-before (has-face-at (- start 1) 'font-latex-math-face);; (get-text-property (+ end 1) 'face )
                          )
         ;; (face-before (get-text-property (- start 1) 'face ))
         )
    (if (and (string-equal "$" substr)
             has-face-after has-face-before)
        (delete-region start end))))


    ;; (progn (message (format "%s"  substr ))
    ;;        (message (format "%s"  (get-text-property start 'face )))
    ;;        (message (format "face after %s"  (get-text-property (+ end 1) 'face )))
    ;;        (message (format "face before %s"  ))
    ;;        ;; (message (format "%s"  (null face)))
    ;;        (message (format "%s" face))
    ;; ;; (message (format "%s" (call-interactively 'delete-char)))
    ;; (if (and
    ;;      (eq substr "$")
    ;;      (null (get-text-property start 'face ))
    ;;      (not (null face)))
    ;;     (call-interactively delete-char)))
;; ))
;; (message "CALLED")
;;   (message (format "%s" face))
;;   (message (format "%s" start))
;;   (message (format "%s" end))
;;   (message (buffer-substring start end))
;; ;; (message (format "%s" (get-text-property start 'face )))
;;   ;; (message (format "%s" (get-text-property (+ 1 start) :face )))
;;   ;; (message (format "%s" (get-text-property (+ 1 start) 'face )))
;;   (message (format "%s" (get-text-property start 'face )))
;;   (cond ((and (seq-contains face 'font-latex-math-face)
;;              (not (seq-contains  (get-text-property (+ 1 start) 'face ) 'font-latex-math-face)))
;;          (message "HERE")
;;         (message (format "%s" face)))
;;         )
;; (cond ((
;;   (progn (message (format "%s" face))
;;   (message (format "%s" start))
;;   (message (format "%s" end)))
;; )))
;; )



(defvar-mode-local latex-mode yank-handled-properties
  '((font-lock-face . yank-handle-font-lock-face-property)
    (face . latex--possibly-remove-math-delimiters)
    ;; ('foreground . latex--possibly-add-math-delimiters)
    (category . yank-handle-category-property)))


#+END_SRC

#+RESULTS:
: yank-handled-properties

** syntax table

#+BEGIN_SRC emacs-lisp
  ;; (modify-syntax-entry ?^ " " tex-mode-syntax-table)
  ;; (modify-syntax-entry ?^ "" )
  ;; (modify-syntax-entry ?^ " " LaTeX-mode-syntax-table)
#+END_SRC

#+RESULTS:

** Copying inside math mode
#+BEGIN_SRC emacs-lisp
;; (defun latex--filter-buffer-substring (beg end &optional delete)
;;   "Return the buffer substring between BEG and END, after filtering.
;; If DELETE is non-nil, delete the text between BEG and END from the buffer.

;; This calls the function that `filter-buffer-substring-function' specifies
;; \(passing the same three arguments that it received) to do the work,
;; and returns whatever it does.  The default function does no filtering,
;; unless a hook has been set.

;; Use `filter-buffer-substring' instead of `buffer-substring',
;; `buffer-substring-no-properties', or `delete-and-extract-region' when
;; you want to allow filtering to take place.  For example, major or minor
;; modes can use `filter-buffer-substring-function' to exclude text properties
;; that are special to a buffer, and should not be copied into other buffers."
;;   (let* ((substr (funcall filter-buffer-substring-function beg end delete)))
;;     (if (<= (length substr) 1)
;;         substr
;;       (let*
;;           ((substr-prefixed (if (and (not (string-prefix-p "$" substr))
;;                                      (eq (get-text-property 0 'face substr) 'font-latex-math-face)
;;                                      )
;;                                 (concat "$" substr)
;;                               substr))
;;            (substr-suffixed (if (and (not (string-suffix-p "$" substr-prefixed))
;;                                      (eq (get-text-property (length substr-prefixed)
;;                                                             'face substr-prefixed) 'font-latex-math-face)
;;                                      )
;;                                 (concat  substr-prefixed "$")
;;                               substr-prefixed))))
;;       )
;;     )
;;   )




;; (defvar latex--region-extract-function
;;   (lambda (method)
;;     (when (region-beginning)
;;       (cond
;;        ((eq method 'bounds)
;;         (list (cons (region-beginning) (region-end))))
;;        ((eq method 'delete-only)
;;         (delete-region (region-beginning) (region-end)))
;;        (t
;;         (latex--filter-buffer-substring (region-beginning) (region-end) method)))))
;;   "Function to get the region's content.
;; Called with one argument METHOD which can be:
;; - nil: return the content as a string (list of strings for
;;   non-contiguous regions).
;; - `delete-only': delete the region; the return value is undefined.
;; - `bounds': return the boundaries of the region as a list of one
;;   or more cons cells of the form (START . END).
;; - anything else: delete the region and return its content
;;   as a string (or list of strings for non-contiguous regions),
;;   after filtering it with `filter-buffer-substring', which
;;   is called, for each contiguous sub-region, with METHOD as its
;;   3rd argument.")
;; (require 'mode-local)
;; (setq-mode-local latex-mode region-extract-function latex--region-extract-function)
;; (add-hook 'latex-mode-hook
;;           (lambda ()
;;             (setq-mode-local latex-mode region-extract-function latex--region-extract-function)))
#+END_SRC

#+RESULTS:

** ans-copy
#+BEGIN_SRC emacs-lisp
(defun ans-copy ()
  (interactive)
  (let ((tmp-file (make-temp-file "ans_" nil nil
                                  (substring-no-properties
                                   (buffer-string) (region-beginning) (region-end)))))
    (kill-new (shell-command-to-string
                  (format "~/.virtualenvs/py3.8/bin/python ~/src/latex2ans.py %s" tmp-file))
                 nil)
))


  ;; (while (< current end)
  ;;   (cond ((and (has-face-at current font-latex-math-face)
  ;;               (string-equal (substring-no-properties current (+ current 1) "$")))
  ;;          (
  ;;          )
#+END_SRC

#+RESULTS:
: ans-copy

https://stackoverflow.com/questions/16270105/why-are-some-unicode-characters-invisible-in-emacs
#+BEGIN_SRC emacs-lisp
(require 'unicode-fonts)
(unicode-fonts-setup)
#+END_SRC

** misc

#+BEGIN_SRC emacs-lisp
    (require 'latex-unicode-math-mode)
    ;; Enable latex-unicode-math-mode automatically for all LaTeX files.
    ;; This converts LaTeX to Unicode inside math environments.
    (add-hook 'LaTeX-mode-hook (lambda () (modify-syntax-entry ?^ " ")))
#+END_SRC

#+RESULTS:
| preview-mode-setup | (lambda nil (modify-syntax-entry 94  )) |

* shell

make sure shell opens in current window

#+BEGIN_SRC emacs-lisp
(add-to-list 'display-buffer-alist
             '("^\\*shell\\*$" . (display-buffer-same-window)))

#+END_SRC

switch between bash and zsh

#+BEGIN_SRC emacs-lisp
(defun set-bash () (interactive) (setq explicit-shell-file-name "/bin/bash"))
(defun set-zsh () (interactive) (setq explicit-shell-file-name "/bin/zsh"))

;; set zsh as default
(set-zsh)
#+END_SRC

#+RESULTS:
: set-zsh

enable command substitution
(https://www.masteringemacs.org/article/shell-comint-secrets-history-commands)

#+BEGIN_SRC emacs-lisp
(define-key shell-mode-map (kbd "SPC") 'comint-magic-space)
#+END_SRC

#+RESULTS:
: comint-magic-space

* javascript
** auto-format
Add node modules bin folder to exec-path

#+BEGIN_SRC emacs-lisp
(push "~/.node_modules_global/bin" exec-path)
(load-file "~/.emacs.d/prettier-emacs/prettier-js.el")
(add-hook 'js-mode-hook 'prettier-js-mode)
(add-hook 'web-mode-hook 'prettier-js-mode)
(eval-after-load 'js-mode (lambda ()
                            (define-key js-mode-map (kbd "C-c C-c")  'indium-reload)))



(add-hook 'js-mode-hook (lambda ()
  (web-mode-set-content-type "jsx")))
(require 'js-format)
  (eval-after-load 'js-mode
    (add-hook 'js-mode-hook
              (lambda()
                (js-format-setup "prettier"))))
(custom-set-variables
  '(js-auto-format-command "prettier")
  '(js-auto-format-command-args "--write --single-quote --no-semi"))
  ;; using "jsbeautify-css" as css formatter
  (eval-after-load 'css-mode
    (add-hook 'css-mode-hook
              (lambda()
                (js-format-setup "jsb-css"))))


(add-hook `js2-mode-hook (lambda ()
                           (global-set-key (kbd "C-c C-v") #'js-format-buffer)))
#+END_SRC

#+RESULTS:
| lambda | nil | (make-variable-buffer-local (quote after-save-hook)) | (add-hook (quote after-save-hook) (quote special-hook)) |

#+RESULTS:
: scss-mode

#+RESULTS:
#+BEGIN_SRC emacs-lisp
(load-file "~/.emacs.d/prettier-emacs/prettier-js.el")
(defun my/activate-tide-mode ()
  "Use hl-identifier-mode only on js or ts buffers."
  (when (and (stringp buffer-file-name)
             (string-match "\\.[tj]sx?\\'" buffer-file-name))
    (tide-setup)
    (tide-hl-identifier-mode)))

(use-package tide
   :hook (web-mode . my/activate-tide-mode)
   :ensure t)
(add-hook 'rjsx-mode-hook 'prettier-js-mode)
#+END_SRC

#+RESULTS:
| prettier-js-mode |

* python
#+BEGIN_SRC emacs-lisp
;; (define-key dump-jump-mode-map (kbd "C-M-p") nil)
;; python-indent-dedent-line-backspace
      (use-package python
        :ensure t
        :mode ("\\.py\\'" . python-mode)
        :interpreter ("python" . python-mode)
        :config
        (setq python-shell-interpreter "ipython"
        ;; python-shell-interpreter-args "--simple-prompt -i --colors=Linux --profile=default")
          python-shell-interpreter-args "")
              (push '("\\.ipynb$" . js2-mode) auto-mode-alist)
        :hook
        (python-mode . (lambda ()
                         "No eldoc for remote files"
                         (let ((name (buffer-file-name)))
                           (when (and name
                                      (> (length name) 5)
                                      (string= "/ssh:" (substring name 0 5)))
                             (eldoc-mode -1))))))

  (setq py-shell-name "ipython")

  (setq python-shell-interpreter-args "-c exec('__import__(\\'readline\\')') -i")

              ;; python-shell-interpreter-args "--simple-prompt -i")
    ;; (defcustom py-shell-name
    ;;   (if (eq system-type 'windows-nt)
    ;;       "C:/Python27/python"
    ;;     ;; "python"
    ;;     "ipython")

    ;; ;;   "A PATH/TO/EXECUTABLE or default value `py-shell' may look for.

    ;; ;; If no shell is specified by command.

    ;; ;; On Windows default is C:/Python27/python
    ;; ;; --there is no garantee it exists, please check your system--

    ;; ;; Else python"
    ;; ;;   :type 'string
    ;; ;;   :tag "py-shell-name"
    ;; ;;   :group 'python-mode)
#+END_SRC

#+RESULTS:
: -c exec('__import__(\'readline\')') -i

** blacken
use-package doesn't seem to work with blacken

#+BEGIN_SRC emacs-lisp
(use-package blacken
  :diminish)
(setq blacken-line-length 79)
(setq blacken-executable "/Users/jeroen/.virtualenvs/py3.8/bin/black")
(add-hook 'python-mode-hook 'blacken-mode 'too-long-lines-mode)

(define-advice org-edit-src-exit (:before (&rest _args) format-python)
  "Run `blacken-buffer' when leaving an org-mode Python source block."
  (when (eq major-mode 'python-mode)
    (blacken-buffer)))

;; (use-package blacken
;;   :ensure t
;;   :bind (:map python-mode-map ("C-c C-b" . blacken-buffer))
;;   :config
;;   (setq blacken-line-length 80)
;;   (add-hook 'python-mode-hook 'blacken-mode))
#+END_SRC

#+RESULTS:
: org-edit-src-exit@format-python

** python jedi (unused)
1. From emacs-jedi readme
#+BEGIN_SRC emacs-lisp
;; (setq jedi:server-command '("pip3" "/Users/jeroen/.emacs.d/.python-environments/default/bin/jediepcserver"))

#+END_SRC

#+RESULTS:

2. Then open Python file.
#+BEGIN_SRC emacs-lisp
;;; Python Jedi
;;; From emacs-jedi readme
;; Type:
;;     M-x jedi:install-server RET
;; Then open Python file.
;; (use-package jedi
;;   :ensure t
;;   ;; :disabled nil
;;   :defer 3
;;   :config
;;   ;; Standard Jedi.el setting
;;   (add-hook 'python-mode-hook 'jedi:setup)
;;   (setq jedi:complete-on-dot t))
#+END_SRC

#+RESULTS:

** elpy
#+BEGIN_SRC emacs-lisp
;;   (use-package elpy
;;     :ensure t
;;     :diminish elpy-mode
;;     :config (elpy-enable))

;;     ;; (add-hook 'elpy-mode-hook 'py-autopep8-enable-on-save)

;;     (custom-set-variables
;;      ;; sudo dnf install python-jedi python3-jedi -y
;;      ;; '(elpy-rpc-backend "jedi")
;;      '(help-at-pt-display-when-idle (quote (flymake-overlay)) nil (help-at-pt))
;;      '(help-at-pt-timer-delay 0.9)
;;      '(tab-width 2))

;;     ;; Do not highlight indentation
;;     ;; (delete 'elpy-module-highlight-indentation elpy-modules)
;;     ;; )
;; (setq elpy-eldoc-show-current-function nil)
#+END_SRC

#+RESULTS:

** xonsh
   #+BEGIN_SRC emacs-lisp
   (push '("\\.xsh$" . python-mode) auto-mode-alist)
   #+END_SRC

   #+RESULTS:
   : ((\.xsh$ . python-mode) (\.ipynb$ . js2-mode) (\.jsx?$ . web-mode) (\.djhtml\' . web-mode) (\.mustache\' . web-mode) (\.erb\' . web-mode) (\.as[cp]x\' . web-mode) (\.[agj]sp\' . web-mode) (\.tpl\.php\' . web-mode) (\.phtml\' . web-mode) (\.odc\' . archive-mode) (\.odf\' . archive-mode) (\.odi\' . archive-mode) (\.otp\' . archive-mode) (\.odp\' . archive-mode) (\.otg\' . archive-mode) (\.odg\' . archive-mode) (\.ots\' . archive-mode) (\.ods\' . archive-mode) (\.odm\' . archive-mode) (\.ott\' . archive-mode) (\.odt\' . archive-mode) (\.[jt]sx?\' . web-mode) (\.php\' . web-mode) (\.html\' . web-mode) (\.hbs\' . web-mode) (\.ejs\' . web-mode) (/Pipfile.lock$ . js2-mode) (/Pipfile$ . conf-mode) (\.xsh$ . python-mode) (\.ipynb$ . js2-mode) (\.py\' . python-mode) (/Users/jeroen/Documents/journal/\(?1:[0-9]\{4\}\)\(?2:[0-9][0-9]\)\(?3:[0-9][0-9]\)\(\.gpg\)?\' . org-journal-mode) (\.gpg\(~\|\.~[0-9]+~\)?\' nil epa-file) (\.hva\' . latex-mode) (\.drv\' . latex-mode) (/git-rebase-todo\' . git-rebase-mode) (\.\(?:md\|markdown\|mkd\|mdown\|mkdn\|mdwn\)\' . markdown-mode) (/nginx/.+\.conf\' . nginx-mode) (nginx\.conf\' . nginx-mode) (/PKGBUILD\' . pkgbuild-mode) (\.toml\' . toml-mode) (\.ts$ . typescript-mode) (\.\(e?ya?\|ra\)ml\' . yaml-mode) (\.elc\' . elisp-byte-code-mode) (\.zst\' nil jka-compr) (\.dz\' nil jka-compr) (\.xz\' nil jka-compr) (\.lzma\' nil jka-compr) (\.lz\' nil jka-compr) (\.g?z\' nil jka-compr) (\.bz2\' nil jka-compr) (\.Z\' nil jka-compr) (\.vr[hi]?\' . vera-mode) (\(?:\.\(?:rbw?\|ru\|rake\|thor\|jbuilder\|rabl\|gemspec\|podspec\)\|/\(?:Gem\|Rake\|Cap\|Thor\|Puppet\|Berks\|Vagrant\|Guard\|Pod\)file\)\' . ruby-mode) (\.re?st\' . rst-mode) (\.py[iw]?\' . python-mode) (\.m\' . octave-maybe-mode) (\.less\' . less-css-mode) (\.scss\' . scss-mode) (\.awk\' . awk-mode) (\.\(u?lpc\|pike\|pmod\(\.in\)?\)\' . pike-mode) (\.idl\' . idl-mode) (\.java\' . java-mode) (\.m\' . objc-mode) (\.ii\' . c++-mode) (\.i\' . c-mode) (\.lex\' . c-mode) (\.y\(acc\)?\' . c-mode) (\.h\' . c-or-c++-mode) (\.c\' . c-mode) (\.\(CC?\|HH?\)\' . c++-mode) (\.[ch]\(pp\|xx\|\+\+\)\' . c++-mode) (\.\(cc\|hh\)\' . c++-mode) (\.\(bat\|cmd\)\' . bat-mode) (\.[sx]?html?\(\.[a-zA-Z_]+\)?\' . mhtml-mode) (\.svgz?\' . image-mode) (\.svgz?\' . xml-mode) (\.x[bp]m\' . image-mode) (\.x[bp]m\' . c-mode) (\.p[bpgn]m\' . image-mode) (\.tiff?\' . image-mode) (\.gif\' . image-mode) (\.png\' . image-mode) (\.jpe?g\' . image-mode) (\.te?xt\' . text-mode) (\.[tT]e[xX]\' . tex-mode) (\.ins\' . tex-mode) (\.ltx\' . latex-mode) (\.dtx\' . doctex-mode) (\.org\' . org-mode) (\.el\' . emacs-lisp-mode) (Project\.ede\' . emacs-lisp-mode) (\.\(scm\|stk\|ss\|sch\)\' . scheme-mode) (\.l\' . lisp-mode) (\.li?sp\' . lisp-mode) (\.[fF]\' . fortran-mode) (\.for\' . fortran-mode) (\.p\' . pascal-mode) (\.pas\' . pascal-mode) (\.\(dpr\|DPR\)\' . delphi-mode) (\.ad[abs]\' . ada-mode) (\.ad[bs]\.dg\' . ada-mode) (\.\([pP]\([Llm]\|erl\|od\)\|al\)\' . perl-mode) (Imakefile\' . makefile-imake-mode) (Makeppfile\(?:\.mk\)?\' . makefile-makepp-mode) (\.makepp\' . makefile-makepp-mode) (\.mk\' . makefile-bsdmake-mode) (\.make\' . makefile-bsdmake-mode) (GNUmakefile\' . makefile-gmake-mode) ([Mm]akefile\' . makefile-bsdmake-mode) (\.am\' . makefile-automake-mode) (\.texinfo\' . texinfo-mode) (\.te?xi\' . texinfo-mode) (\.[sS]\' . asm-mode) (\.asm\' . asm-mode) (\.css\' . css-mode) (\.mixal\' . mixal-mode) (\.gcov\' . compilation-mode) (/\.[a-z0-9-]*gdbinit . gdb-script-mode) (-gdb\.gdb . gdb-script-mode) ([cC]hange\.?[lL]og?\' . change-log-mode) ([cC]hange[lL]og[-.][0-9]+\' . change-log-mode) (\$CHANGE_LOG\$\.TXT . change-log-mode) (\.scm\.[0-9]*\' . scheme-mode) (\.[ckz]?sh\'\|\.shar\'\|/\.z?profile\' . sh-mode) (\.bash\' . sh-mode) (\(/\|\`\)\.\(bash_\(profile\|history\|log\(in\|out\)\)\|z?log\(in\|out\)\)\' . sh-mode) (\(/\|\`\)\.\(shrc\|zshrc\|m?kshrc\|bashrc\|t?cshrc\|esrc\)\' . sh-mode) (\(/\|\`\)\.\([kz]shenv\|xinitrc\|startxrc\|xsession\)\' . sh-mode) (\.m?spec\' . sh-mode) (\.m[mes]\' . nroff-mode) (\.man\' . nroff-mode) (\.sty\' . latex-mode) (\.cl[so]\' . latex-mode) (\.bbl\' . latex-mode) (\.bib\' . bibtex-mode) (\.bst\' . bibtex-style-mode) (\.sql\' . sql-mode) (\(acinclude\|aclocal\|acsite\)\.m4\' . autoconf-mode) (\.m[4c]\' . m4-mode) (\.mf\' . metafont-mode) (\.mp\' . metapost-mode) (\.vhdl?\' . vhdl-mode) (\.article\' . text-mode) (\.letter\' . text-mode) (\.i?tcl\' . tcl-mode) (\.exp\' . tcl-mode) (\.itk\' . tcl-mode) (\.icn\' . icon-mode) (\.sim\' . simula-mode) (\.mss\' . scribe-mode) (\.f9[05]\' . f90-mode) (\.f0[38]\' . f90-mode) (\.indent\.pro\' . fundamental-mode) (\.\(pro\|PRO\)\' . idlwave-mode) (\.srt\' . srecode-template-mode) (\.prolog\' . prolog-mode) (\.tar\' . tar-mode) (\.\(arc\|zip\|lzh\|lha\|zoo\|[jew]ar\|xpi\|rar\|cbr\|7z\|ARC\|ZIP\|LZH\|LHA\|ZOO\|[JEW]AR\|XPI\|RAR\|CBR\|7Z\)\' . archive-mode) (\.oxt\' . archive-mode) (\.\(deb\|[oi]pk\)\' . archive-mode) (\`/tmp/Re . text-mode) (/Message[0-9]*\' . text-mode) (\`/tmp/fol/ . text-mode) (\.oak\' . scheme-mode) (\.sgml?\' . sgml-mode) (\.x[ms]l\' . xml-mode) (\.dbk\' . xml-mode) (\.dtd\' . sgml-mode) (\.ds\(ss\)?l\' . dsssl-mode) (\.js[mx]?\' . javascript-mode) (\.har\' . javascript-mode) (\.json\' . javascript-mode) (\.[ds]?va?h?\' . verilog-mode) (\.by\' . bovine-grammar-mode) (\.wy\' . wisent-grammar-mode) ([:/\]\..*\(emacs\|gnus\|viper\)\' . emacs-lisp-mode) (\`\..*emacs\' . emacs-lisp-mode) ([:/]_emacs\' . emacs-lisp-mode) (/crontab\.X*[0-9]+\' . shell-script-mode) (\.ml\' . lisp-mode) (\.ld[si]?\' . ld-script-mode) (ld\.?script\' . ld-script-mode) (\.xs\' . c-mode) (\.x[abdsru]?[cnw]?\' . ld-script-mode) (\.zone\' . dns-mode) (\.soa\' . dns-mode) (\.asd\' . lisp-mode) (\.\(asn\|mib\|smi\)\' . snmp-mode) (\.\(as\|mi\|sm\)2\' . snmpv2-mode) (\.\(diffs?\|patch\|rej\)\' . diff-mode) (\.\(dif\|pat\)\' . diff-mode) (\.[eE]?[pP][sS]\' . ps-mode) (\.\(?:PDF\|DVI\|OD[FGPST]\|DOCX\|XLSX?\|PPTX?\|pdf\|djvu\|dvi\|od[fgpst]\|docx\|xlsx?\|pptx?\)\' . doc-view-mode-maybe) (configure\.\(ac\|in\)\' . autoconf-mode) (\.s\(v\|iv\|ieve\)\' . sieve-mode) (BROWSE\' . ebrowse-tree-mode) (\.ebrowse\' . ebrowse-tree-mode) (#\*mail\* . mail-mode) (\.g\' . antlr-mode) (\.mod\' . m2-mode) (\.ses\' . ses-mode) (\.docbook\' . sgml-mode) (\.com\' . dcl-mode) (/config\.\(?:bat\|log\)\' . fundamental-mode) (/\.\(authinfo\|netrc\)\' . authinfo-mode) (\.\(?:[iI][nN][iI]\|[lL][sS][tT]\|[rR][eE][gG]\|[sS][yY][sS]\)\' . conf-mode) (\.la\' . conf-unix-mode) (\.ppd\' . conf-ppd-mode) (java.+\.conf\' . conf-javaprop-mode) (\.properties\(?:\.[a-zA-Z0-9._-]+\)?\' . conf-javaprop-mode) (\.toml\' . conf-toml-mode) (\.desktop\' . conf-desktop-mode) (/\.redshift\.conf\' . conf-windows-mode) (\`/etc/\(?:DIR_COLORS\|ethers\|.?fstab\|.*hosts\|lesskey\|login\.?de\(?:fs\|vperm\)\|magic\|mtab\|pam\.d/.*\|permissions\(?:\.d/.+\)?\|protocols\|rpc\|services\)\' . conf-space-mode) (\`/etc/\(?:acpid?/.+\|aliases\(?:\.d/.+\)?\|default/.+\|group-?\|hosts\..+\|inittab\|ksysguarddrc\|opera6rc\|passwd-?\|shadow-?\|sysconfig/.+\)\' . conf-mode) ([cC]hange[lL]og[-.][-0-9a-z]+\' . change-log-mode) (/\.?\(?:gitconfig\|gnokiirc\|hgrc\|kde.*rc\|mime\.types\|wgetrc\)\' . conf-mode) (/\.\(?:asound\|enigma\|fetchmail\|gltron\|gtk\|hxplayer\|mairix\|mbsync\|msmtp\|net\|neverball\|nvidia-settings-\|offlineimap\|qt/.+\|realplayer\|reportbug\|rtorrent\.\|screen\|scummvm\|sversion\|sylpheed/.+\|xmp\)rc\' . conf-mode) (/\.\(?:gdbtkinit\|grip\|mpdconf\|notmuch-config\|orbital/.+txt\|rhosts\|tuxracer/options\)\' . conf-mode) (/\.?X\(?:default\|resource\|re\)s\> . conf-xdefaults-mode) (/X11.+app-defaults/\|\.ad\' . conf-xdefaults-mode) (/X11.+locale/.+/Compose\' . conf-colon-mode) (/X11.+locale/compose\.dir\' . conf-javaprop-mode) (\.~?[0-9]+\.[0-9][-.0-9]*~?\' nil t) (\.\(?:orig\|in\|[bB][aA][kK]\)\' nil t) ([/.]c\(?:on\)?f\(?:i?g\)?\(?:\.[a-zA-Z0-9._-]+\)?\' . conf-mode-maybe) (\.[1-9]\' . nroff-mode) (\.art\' . image-mode) (\.avs\' . image-mode) (\.bmp\' . image-mode) (\.cmyk\' . image-mode) (\.cmyka\' . image-mode) (\.crw\' . image-mode) (\.dcr\' . image-mode) (\.dcx\' . image-mode) (\.dng\' . image-mode) (\.dpx\' . image-mode) (\.fax\' . image-mode) (\.hrz\' . image-mode) (\.icb\' . image-mode) (\.icc\' . image-mode) (\.icm\' . image-mode) (\.ico\' . image-mode) (\.icon\' . image-mode) (\.jbg\' . image-mode) (\.jbig\' . image-mode) (\.jng\' . image-mode) (\.jnx\' . image-mode) (\.miff\' . image-mode) (\.mng\' . image-mode) (\.mvg\' . image-mode) (\.otb\' . image-mode) (\.p7\' . image-mode) (\.pcx\' . image-mode) (\.pdb\' . image-mode) (\.pfa\' . image-mode) (\.pfb\' . image-mode) (\.picon\' . image-mode) (\.pict\' . image-mode) (\.rgb\' . image-mode) (\.rgba\' . image-mode) (\.tga\' . image-mode) (\.wbmp\' . image-mode) (\.webp\' . image-mode) (\.wmf\' . image-mode) (\.wpg\' . image-mode) (\.xcf\' . image-mode) (\.xmp\' . image-mode) (\.xwd\' . image-mode) (\.yuv\' . image-mode) (\.tgz\' . tar-mode) (\.tbz2?\' . tar-mode) (\.txz\' . tar-mode) (\.tzst\' . tar-mode))

** pipenv
   #+BEGIN_SRC emacs-lisp
     (push '("/Pipfile$" . conf-mode) auto-mode-alist)
     (push '("/Pipfile.lock$" . js2-mode) auto-mode-alist)
   #+END_SRC

   #+RESULTS:
   : ((/Pipfile.lock$ . js2-mode) (/Pipfile$ . conf-mode) (\.xsh$ . python-mode) (\.ipynb$ . js2-mode) (\.jsx?$ . web-mode) (\.djhtml\' . web-mode) (\.mustache\' . web-mode) (\.erb\' . web-mode) (\.as[cp]x\' . web-mode) (\.[agj]sp\' . web-mode) (\.tpl\.php\' . web-mode) (\.phtml\' . web-mode) (\.odc\' . archive-mode) (\.odf\' . archive-mode) (\.odi\' . archive-mode) (\.otp\' . archive-mode) (\.odp\' . archive-mode) (\.otg\' . archive-mode) (\.odg\' . archive-mode) (\.ots\' . archive-mode) (\.ods\' . archive-mode) (\.odm\' . archive-mode) (\.ott\' . archive-mode) (\.odt\' . archive-mode) (\.[jt]sx?\' . web-mode) (\.php\' . web-mode) (\.html\' . web-mode) (\.hbs\' . web-mode) (\.ejs\' . web-mode) (/Pipfile.lock$ . js2-mode) (/Pipfile$ . conf-mode) (\.xsh$ . python-mode) (\.ipynb$ . js2-mode) (\.py\' . python-mode) (/Users/jeroen/Documents/journal/\(?1:[0-9]\{4\}\)\(?2:[0-9][0-9]\)\(?3:[0-9][0-9]\)\(\.gpg\)?\' . org-journal-mode) (\.gpg\(~\|\.~[0-9]+~\)?\' nil epa-file) (\.hva\' . latex-mode) (\.drv\' . latex-mode) (/git-rebase-todo\' . git-rebase-mode) (\.\(?:md\|markdown\|mkd\|mdown\|mkdn\|mdwn\)\' . markdown-mode) (/nginx/.+\.conf\' . nginx-mode) (nginx\.conf\' . nginx-mode) (/PKGBUILD\' . pkgbuild-mode) (\.toml\' . toml-mode) (\.ts$ . typescript-mode) (\.\(e?ya?\|ra\)ml\' . yaml-mode) (\.elc\' . elisp-byte-code-mode) (\.zst\' nil jka-compr) (\.dz\' nil jka-compr) (\.xz\' nil jka-compr) (\.lzma\' nil jka-compr) (\.lz\' nil jka-compr) (\.g?z\' nil jka-compr) (\.bz2\' nil jka-compr) (\.Z\' nil jka-compr) (\.vr[hi]?\' . vera-mode) (\(?:\.\(?:rbw?\|ru\|rake\|thor\|jbuilder\|rabl\|gemspec\|podspec\)\|/\(?:Gem\|Rake\|Cap\|Thor\|Puppet\|Berks\|Vagrant\|Guard\|Pod\)file\)\' . ruby-mode) (\.re?st\' . rst-mode) (\.py[iw]?\' . python-mode) (\.m\' . octave-maybe-mode) (\.less\' . less-css-mode) (\.scss\' . scss-mode) (\.awk\' . awk-mode) (\.\(u?lpc\|pike\|pmod\(\.in\)?\)\' . pike-mode) (\.idl\' . idl-mode) (\.java\' . java-mode) (\.m\' . objc-mode) (\.ii\' . c++-mode) (\.i\' . c-mode) (\.lex\' . c-mode) (\.y\(acc\)?\' . c-mode) (\.h\' . c-or-c++-mode) (\.c\' . c-mode) (\.\(CC?\|HH?\)\' . c++-mode) (\.[ch]\(pp\|xx\|\+\+\)\' . c++-mode) (\.\(cc\|hh\)\' . c++-mode) (\.\(bat\|cmd\)\' . bat-mode) (\.[sx]?html?\(\.[a-zA-Z_]+\)?\' . mhtml-mode) (\.svgz?\' . image-mode) (\.svgz?\' . xml-mode) (\.x[bp]m\' . image-mode) (\.x[bp]m\' . c-mode) (\.p[bpgn]m\' . image-mode) (\.tiff?\' . image-mode) (\.gif\' . image-mode) (\.png\' . image-mode) (\.jpe?g\' . image-mode) (\.te?xt\' . text-mode) (\.[tT]e[xX]\' . tex-mode) (\.ins\' . tex-mode) (\.ltx\' . latex-mode) (\.dtx\' . doctex-mode) (\.org\' . org-mode) (\.el\' . emacs-lisp-mode) (Project\.ede\' . emacs-lisp-mode) (\.\(scm\|stk\|ss\|sch\)\' . scheme-mode) (\.l\' . lisp-mode) (\.li?sp\' . lisp-mode) (\.[fF]\' . fortran-mode) (\.for\' . fortran-mode) (\.p\' . pascal-mode) (\.pas\' . pascal-mode) (\.\(dpr\|DPR\)\' . delphi-mode) (\.ad[abs]\' . ada-mode) (\.ad[bs]\.dg\' . ada-mode) (\.\([pP]\([Llm]\|erl\|od\)\|al\)\' . perl-mode) (Imakefile\' . makefile-imake-mode) (Makeppfile\(?:\.mk\)?\' . makefile-makepp-mode) (\.makepp\' . makefile-makepp-mode) (\.mk\' . makefile-bsdmake-mode) (\.make\' . makefile-bsdmake-mode) (GNUmakefile\' . makefile-gmake-mode) ([Mm]akefile\' . makefile-bsdmake-mode) (\.am\' . makefile-automake-mode) (\.texinfo\' . texinfo-mode) (\.te?xi\' . texinfo-mode) (\.[sS]\' . asm-mode) (\.asm\' . asm-mode) (\.css\' . css-mode) (\.mixal\' . mixal-mode) (\.gcov\' . compilation-mode) (/\.[a-z0-9-]*gdbinit . gdb-script-mode) (-gdb\.gdb . gdb-script-mode) ([cC]hange\.?[lL]og?\' . change-log-mode) ([cC]hange[lL]og[-.][0-9]+\' . change-log-mode) (\$CHANGE_LOG\$\.TXT . change-log-mode) (\.scm\.[0-9]*\' . scheme-mode) (\.[ckz]?sh\'\|\.shar\'\|/\.z?profile\' . sh-mode) (\.bash\' . sh-mode) (\(/\|\`\)\.\(bash_\(profile\|history\|log\(in\|out\)\)\|z?log\(in\|out\)\)\' . sh-mode) (\(/\|\`\)\.\(shrc\|zshrc\|m?kshrc\|bashrc\|t?cshrc\|esrc\)\' . sh-mode) (\(/\|\`\)\.\([kz]shenv\|xinitrc\|startxrc\|xsession\)\' . sh-mode) (\.m?spec\' . sh-mode) (\.m[mes]\' . nroff-mode) (\.man\' . nroff-mode) (\.sty\' . latex-mode) (\.cl[so]\' . latex-mode) (\.bbl\' . latex-mode) (\.bib\' . bibtex-mode) (\.bst\' . bibtex-style-mode) (\.sql\' . sql-mode) (\(acinclude\|aclocal\|acsite\)\.m4\' . autoconf-mode) (\.m[4c]\' . m4-mode) (\.mf\' . metafont-mode) (\.mp\' . metapost-mode) (\.vhdl?\' . vhdl-mode) (\.article\' . text-mode) (\.letter\' . text-mode) (\.i?tcl\' . tcl-mode) (\.exp\' . tcl-mode) (\.itk\' . tcl-mode) (\.icn\' . icon-mode) (\.sim\' . simula-mode) (\.mss\' . scribe-mode) (\.f9[05]\' . f90-mode) (\.f0[38]\' . f90-mode) (\.indent\.pro\' . fundamental-mode) (\.\(pro\|PRO\)\' . idlwave-mode) (\.srt\' . srecode-template-mode) (\.prolog\' . prolog-mode) (\.tar\' . tar-mode) (\.\(arc\|zip\|lzh\|lha\|zoo\|[jew]ar\|xpi\|rar\|cbr\|7z\|ARC\|ZIP\|LZH\|LHA\|ZOO\|[JEW]AR\|XPI\|RAR\|CBR\|7Z\)\' . archive-mode) (\.oxt\' . archive-mode) (\.\(deb\|[oi]pk\)\' . archive-mode) (\`/tmp/Re . text-mode) (/Message[0-9]*\' . text-mode) (\`/tmp/fol/ . text-mode) (\.oak\' . scheme-mode) (\.sgml?\' . sgml-mode) (\.x[ms]l\' . xml-mode) (\.dbk\' . xml-mode) (\.dtd\' . sgml-mode) (\.ds\(ss\)?l\' . dsssl-mode) (\.js[mx]?\' . javascript-mode) (\.har\' . javascript-mode) (\.json\' . javascript-mode) (\.[ds]?va?h?\' . verilog-mode) (\.by\' . bovine-grammar-mode) (\.wy\' . wisent-grammar-mode) ([:/\]\..*\(emacs\|gnus\|viper\)\' . emacs-lisp-mode) (\`\..*emacs\' . emacs-lisp-mode) ([:/]_emacs\' . emacs-lisp-mode) (/crontab\.X*[0-9]+\' . shell-script-mode) (\.ml\' . lisp-mode) (\.ld[si]?\' . ld-script-mode) (ld\.?script\' . ld-script-mode) (\.xs\' . c-mode) (\.x[abdsru]?[cnw]?\' . ld-script-mode) (\.zone\' . dns-mode) (\.soa\' . dns-mode) (\.asd\' . lisp-mode) (\.\(asn\|mib\|smi\)\' . snmp-mode) (\.\(as\|mi\|sm\)2\' . snmpv2-mode) (\.\(diffs?\|patch\|rej\)\' . diff-mode) (\.\(dif\|pat\)\' . diff-mode) (\.[eE]?[pP][sS]\' . ps-mode) (\.\(?:PDF\|DVI\|OD[FGPST]\|DOCX\|XLSX?\|PPTX?\|pdf\|djvu\|dvi\|od[fgpst]\|docx\|xlsx?\|pptx?\)\' . doc-view-mode-maybe) (configure\.\(ac\|in\)\' . autoconf-mode) (\.s\(v\|iv\|ieve\)\' . sieve-mode) (BROWSE\' . ebrowse-tree-mode) (\.ebrowse\' . ebrowse-tree-mode) (#\*mail\* . mail-mode) (\.g\' . antlr-mode) (\.mod\' . m2-mode) (\.ses\' . ses-mode) (\.docbook\' . sgml-mode) (\.com\' . dcl-mode) (/config\.\(?:bat\|log\)\' . fundamental-mode) (/\.\(authinfo\|netrc\)\' . authinfo-mode) (\.\(?:[iI][nN][iI]\|[lL][sS][tT]\|[rR][eE][gG]\|[sS][yY][sS]\)\' . conf-mode) (\.la\' . conf-unix-mode) (\.ppd\' . conf-ppd-mode) (java.+\.conf\' . conf-javaprop-mode) (\.properties\(?:\.[a-zA-Z0-9._-]+\)?\' . conf-javaprop-mode) (\.toml\' . conf-toml-mode) (\.desktop\' . conf-desktop-mode) (/\.redshift\.conf\' . conf-windows-mode) (\`/etc/\(?:DIR_COLORS\|ethers\|.?fstab\|.*hosts\|lesskey\|login\.?de\(?:fs\|vperm\)\|magic\|mtab\|pam\.d/.*\|permissions\(?:\.d/.+\)?\|protocols\|rpc\|services\)\' . conf-space-mode) (\`/etc/\(?:acpid?/.+\|aliases\(?:\.d/.+\)?\|default/.+\|group-?\|hosts\..+\|inittab\|ksysguarddrc\|opera6rc\|passwd-?\|shadow-?\|sysconfig/.+\)\' . conf-mode) ([cC]hange[lL]og[-.][-0-9a-z]+\' . change-log-mode) (/\.?\(?:gitconfig\|gnokiirc\|hgrc\|kde.*rc\|mime\.types\|wgetrc\)\' . conf-mode) (/\.\(?:asound\|enigma\|fetchmail\|gltron\|gtk\|hxplayer\|mairix\|mbsync\|msmtp\|net\|neverball\|nvidia-settings-\|offlineimap\|qt/.+\|realplayer\|reportbug\|rtorrent\.\|screen\|scummvm\|sversion\|sylpheed/.+\|xmp\)rc\' . conf-mode) (/\.\(?:gdbtkinit\|grip\|mpdconf\|notmuch-config\|orbital/.+txt\|rhosts\|tuxracer/options\)\' . conf-mode) (/\.?X\(?:default\|resource\|re\)s\> . conf-xdefaults-mode) (/X11.+app-defaults/\|\.ad\' . conf-xdefaults-mode) (/X11.+locale/.+/Compose\' . conf-colon-mode) (/X11.+locale/compose\.dir\' . conf-javaprop-mode) (\.~?[0-9]+\.[0-9][-.0-9]*~?\' nil t) (\.\(?:orig\|in\|[bB][aA][kK]\)\' nil t) ([/.]c\(?:on\)?f\(?:i?g\)?\(?:\.[a-zA-Z0-9._-]+\)?\' . conf-mode-maybe) (\.[1-9]\' . nroff-mode) (\.art\' . image-mode) (\.avs\' . image-mode) (\.bmp\' . image-mode) (\.cmyk\' . image-mode) (\.cmyka\' . image-mode) (\.crw\' . image-mode) (\.dcr\' . image-mode) (\.dcx\' . image-mode) (\.dng\' . image-mode) (\.dpx\' . image-mode) (\.fax\' . image-mode) (\.hrz\' . image-mode) (\.icb\' . image-mode) (\.icc\' . image-mode) (\.icm\' . image-mode) (\.ico\' . image-mode) (\.icon\' . image-mode) (\.jbg\' . image-mode) (\.jbig\' . image-mode) (\.jng\' . image-mode) (\.jnx\' . image-mode) (\.miff\' . image-mode) (\.mng\' . image-mode) (\.mvg\' . image-mode) (\.otb\' . image-mode) (\.p7\' . image-mode) (\.pcx\' . image-mode) (\.pdb\' . image-mode) (\.pfa\' . image-mode) (\.pfb\' . image-mode) (\.picon\' . image-mode) (\.pict\' . image-mode) (\.rgb\' . image-mode) (\.rgba\' . image-mode) (\.tga\' . image-mode) (\.wbmp\' . image-mode) (\.webp\' . image-mode) (\.wmf\' . image-mode) (\.wpg\' . image-mode) (\.xcf\' . image-mode) (\.xmp\' . image-mode) (\.xwd\' . image-mode) (\.yuv\' . image-mode) (\.tgz\' . tar-mode) (\.tbz2?\' . tar-mode) (\.txz\' . tar-mode) (\.tzst\' . tar-mode))

** bug fix
#+BEGIN_SRC emacs-lisp
  ;; Fix Python loading bug in emacs25
  (with-eval-after-load 'python
    (defun python-shell-completion-native-try ()
      "Return non-nil if can trigger native completion."
      (let ((python-shell-completion-native-enable t)
            (python-shell-completion-native-output-timeout
             python-shell-completion-native-try-output-timeout))
        (python-shell-completion-native-get-completions
         (get-buffer-process (current-buffer))
         nil "_"))))
#+END_SRC

#+RESULTS:
: python-shell-completion-native-try

** unused
#+BEGIN_SRC emacs-lisp
  (setq
   ;; python-shell-interpreter "python"
   ;; python-shell-interpreter-args "--colors=Linux --profile=default"
   python-shell-interpreter-interactive-arg "--simple-prompt -i"
   python-shell-prompt-regexp "In \\[[0-9]+\\]: "
   python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: "
   python-shell-completion-setup-code
   "from IPython.core.completerlib import module_completion"
   python-shell-completion-module-string-code
   "';'.join(module_completion('''%s'''))\n"
   python-shell-completion-string-code
   "';'.join(get_ipython().Completer.all_completions('''%s'''))\n")
  ;; (setq python-shell-interpreter "ipython"
  ;;       python-shell-interpreter-args "--simple-prompt"
  ;;       py-python-command-args '("--matplotlib")
  ;;       python-shell-prompt-regexp "In \\[[0-9]+\\]: "
  ;;       python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: "
  ;;       python-shell-completion-setup-code
  ;;       "from IPython.core.completerlib import module_completion"
  ;;       python-shell-completion-module-string-code
  ;;       "';'.join(module_completion('''%s'''))\n"
  ;;       python-shell-completion-string-code
  ;;       "';'.join(get_ipython().Completer.all_completions('''%s'''))\n"

  ;;       python-check-command "pylint"
  ;;       python-indent-offset 2
  ;;       py-autopep8-options '("--max-line-length=80")
  ;;       )

  ;; (add-hook 'python-mode-hook 'jedi:setup)
  ;; (setq jedi:complete-on-dot t)

#+END_SRC

#+RESULTS:
: ';'.join(get_ipython().Completer.all_completions('''%s'''))

** virtualenv
#+BEGIN_SRC emacs-lisp
  (use-package virtualenvwrapper
    :ensure t
    :config
    (venv-initialize-interactive-shells) ;; if you want interactive shell support
    (venv-initialize-eshell)             ;; if you want eshell support
    ;; note that setting `venv-location` is not necessary if you
    ;; use the default location (`~/.virtualenvs`), or if the
    ;; the environment variable `WORKON_HOME` points to the right place
    (setq venv-location "~/.virtualenvs/"))


#+END_SRC

#+RESULTS:
: t

** info
#+BEGIN_SRC emacs-lisp
  (require 'info-look)

  (info-lookup-add-help
   :mode 'python-mode
   :regexp "[[:alnum:]_]+"
   :doc-spec '(("(python)Index" nil "")))
#+END_SRC

#+RESULTS:

** Inferior python mode
#+BEGIN_SRC emacs-lisp
  ;;     (load-file "/home/paul/.emacs.d/too-long-lines-mode/too-long-lines-mode.el")
  ;; (add-hook `inferior-python-mode-hook (too-long-lines-mode))

#+END_SRC

#+RESULTS:

#+BEGIN_SRC emacs-lisp
(define-key python-mode-map (kbd "DEL") nil)

(fset 'ipython-cpaste
   (kmacro-lambda-form [?\M-> ?% ?c ?p ?a ?s ?t ?e return ?\M-x ?y ?a ?n ?k ?\C-m return ?- ?- return] 0 "%d"))

(define-key inferior-python-mode-map (kbd "C-M-y") 'ipython-cpaste)
(define-key shell-mode-map (kbd "C-M-y") 'ipython-cpaste)
#+END_SRC

#+RESULTS:
: ipython-cpaste
** conda envs
#+BEGIN_SRC emacs-lisp
(setenv "WORKON_HOME" "/usr/local/Caskroom/miniconda/base/envs")
#+END_SRC

#+RESULTS:
: /usr/local/Caskroom/miniconda/base/envs
** django
#+BEGIN_SRC emacs-lisp
;; (defun django-shell ()
;;   (interactive)
;;   (let ((python-shell-interpreter "python")
;;     (python-shell-interpreter-args "-i /home/paul/projects/plekje/api/manage.py shell_plus"))
;;     (run-python)))
;; # (setq python-shell-interpreter "python"
;; #       python-shell-interpreter-args "-i /home/paul/projects/plekje/api/manage.py shell_plus")
#+END_SRC

#+RESULTS:

** jupyter
Let's write a function that gets the token

#+begin_src emacs-lisp
(defun jupyter-insert-token ()
  (interactive)
  (let ((output (shell-command-to-string "jupyter notebook list")))
        (insert (first (split-string (second (split-string output "token=")) " " )))
))
#+end_src

#+RESULTS:
: jupyter-insert-token

#+begin_src emacs-lisp
(defun pip-venv-mode () (interactive)
(setq venv-location "~/.virtualenvs/"))

(defun conda-venv-mode () (interactive)
(setq venv-location "/usr/local/Caskroom/miniconda/base/envs"))
#+end_src

#+RESULTS:
: conda-venv-mode

** pygen

#+BEGIN_SRC emacs-lisp
;; (use-package pygen
;;   :ensure t)
;; (add-hook 'python-mode-hook 'pygen-mode)
#+END_SRC

#+RESULTS:
| pygen-mode | (closure (t) nil (setq imenu-create-index-function py--imenu-create-index-function) (setq indent-tabs-mode py-indent-tabs-mode)) | (lambda nil No eldoc for remote files (let ((name (buffer-file-name))) (when (and name (> (length name) 5) (string= /ssh: (substring name 0 5))) (eldoc-mode -1)))) | elpy-mode | (lambda nil No eldoc for remote files (let ((name (buffer-file-name))) (if (and name (> (length name) 5) (string= /ssh: (substring name 0 5))) (progn (eldoc-mode -1))))) | blacken-mode |

* icicles

#+BEGIN_SRC emacs-lisp
;; (load "~/.emacs.d/icicles-install")
;; (customize-variable' "icicle-download-dir" "~/.emacs.d/icicles")


;; (add-to-list 'load-path "~/.emacs.d/icicles")
;; (require 'icicles)

;; (icy-mode 1)
#+END_SRC

#+RESULTS:
* highlight syntax errors in json
This requires =jsonlint=. Install with =npm install jsonlint -g=.

#+BEGIN_SRC emacs-lisp
(delete 'flycheck-disabled-checkers "json-jsonlist")
(use-package flycheck
  :ensure t)
(flycheck-add-mode 'json-jsonlint 'json-mode)
(add-hook 'json-mode-hook 'flycheck-mode)
#+END_SRC

#+RESULTS:
| flycheck-mode |

* inline math results

#+BEGIN_SRC emacs-lisp
(defun eval-and-replace ()
  "Replace the preceding sexp with its value."
  (interactive)
  (backward-kill-sexp)
  (condition-case nil
      (prin1 (eval (read (current-kill 0)))
             (current-buffer))
    (error (message "Invalid expression")
           (insert (current-kill 0)))))

(bind-key* "C-x M-e" 'eval-and-replace)
#+END_SRC

#+RESULTS:
: eval-and-replace
* ace-window

#+BEGIN_SRC emacs-lisp
(use-package ace-window
  :ensure t)
(global-set-key (kbd "M-o") 'ace-window)
(setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
(defvar aw-dispatch-alist
  '((?x aw-delete-window "Delete Window")
  (?m aw-swap-window "Swap Windows")
  (?M aw-move-window "Move Window")
  (?c aw-copy-window "Copy Window")
  (?j aw-switch-buffer-in-window "Select Buffer")
  (?n aw-flip-window)
  (?u aw-switch-buffer-other-window "Switch Buffer Other Window")
  (?c aw-split-window-fair "Split Fair Window")
  (?v aw-split-window-vert "Split Vert Window")
  (?b aw-split-window-horz "Split Horz Window")
  (?o delete-other-windows "Delete Other Windows")
  (?? aw-show-dispatch-help))
  "List of actions for `aw-dispatch-default'.")
#+END_SRC

#+RESULTS:
: aw-dispatch-alist
* emacs-dashboard
the =dashboard= package changes the splash screen into something useful.

enable it:
#+BEGIN_SRC emacs-lisp
(defun dashboard-remember (list-size)
  (insert "remember:
    [M--] negative argument
    [C-M-v & M-- C-M-v] scroll other window down & up
    [M-m] move to indentation
    [C-c C-j in python] imenu
    [M-{ & M-}] traverse paragraph-type blocks
"))
(use-package dashboard
  :ensure t
  :init
  (progn
    (setq dashboard-items '((recents . 6)
                            (projects . 8)
                            (remember . 1)))
    (setq dashboard-banner-logo-title "jpjmacs")
    (setq dashboard-startup-banner "~/.emacs.d/araki_banner.png")
    (setq dashboard-set-navigator t)
    (setq dashboard-set-footer nil)
    (setq dashboard-navigator-buttons
      `(;; line1
        (
         (nil "shell-fxr" "open shell on fxr" (lambda (&rest _) (shell-fxr)))
         (nil "shell-lisa" "open shell on lisa-dl" (lambda (&rest _) (shell-lisa-dl)))
        )
       )
      )
    )
  :config
  (dashboard-setup-startup-hook))
(add-to-list 'dashboard-item-generators  '(remember . dashboard-remember))
#+END_SRC

#+RESULTS:
: t
* focus mode (centered editing)

olivetti provides that centered buffer:

#+BEGIN_SRC emacs-lisp
(use-package olivetti
  :ensure t
  :diminish
  :config
  (setq olivetti-body-width 0.7)
  (setq olivetti-minimum-body-width 100)
  (setq olivetti-recall-visual-line-mode-entry-state t))

(defun focus ()
  (interactive)
  (delete-other-windows)
  (olivetti-mode))

(defun defocus ()
  (interactive)
  (olivetti-mode))
#+END_SRC

#+RESULTS:
: defocus
* random utils

** copy org block as ans block

#+BEGIN_SRC emacs-lisp
(defun org-copy-section-as-tex ()
  (interactive)
  (save-excursion
    (call-interactively 'org-previous-visible-heading)
    (call-interactively 'org-mark-element)
    (next-line)
    (tex2ans (buffer-substring (region-beginning)
                               (region-end)))))

(defun tex2ans (s)
  (let ((tmp-file (make-temp-file "ans_" nil nil s)))
    (kill-new (shell-command-to-string (format "~/.virtualenvs/py3.8/bin/python ~/.emacs.d/scripts/latex2ans.py %s"
                                               tmp-file))
              nil)))

(define-key org-mode-map (kbd "C-c C-8") 'org-copy-section-as-tex)
#+END_SRC

#+RESULTS:
: org-copy-section-as-tex
* windows os
run bash on windows:

#+BEGIN_SRC emacs-lisp
(defun shell-on-windows ()
  (let ((explicit-shell-file-name "C:/Windows/System32/bash.exe"))
    (shell)))
#+END_SRC

#+RESULTS:
: shell-on-windows

* mode-line

** minor modes

diminish.el (re)moves the text some minor modes add to the minor lighter text
in mode-line.

#+BEGIN_SRC emacs-lisp
;; (use-package diminish
;;   :straight t
;;   :config
;;   (diminish 'projectile-mode)
;;   (diminish 'auto-fill-mode))
#+END_SRC

however, i'd like to whitelist minor modes that /are/ allowed instead of having
to blacklist all i /don't/ want. for that, there exists =rich-minority=:

[it doesn't work tho. so using diminish for now]

#+BEGIN_SRC emacs-lisp
(use-package rich-minority
  :straight t
  :config
  ;; (setq rm-blacklist "Projectile.*")
  (setq rm-whitelist
        '(
          ;; " Fill"
          ;; "yas"
          "mc:*"
          " Def"
          ))
  (setq rm-whitelist-regexps
        '(
          "mc:*"
          " Def"
          ))
  (setq rm-whitelist (mapconcat 'identity rm-whitelist-regexps "\\|"))
  ;; (setq rm-whitelist
  ;;     (format "^ \(%s\)$"
  ;;             (mapconcat #'identity
  ;;                        rm-whitelist-regexps
  ;;                        "\\|")))
  (rich-minority-mode 1))
#+END_SRC

#+RESULTS:
: t

** hide mode-line, put at header-line spot

#+BEGIN_SRC emacs-lisp
;; status-icon to the left of filename
(defun render-mode-line-status-icon (read-only modified)
  (if read-only
      ""
    (if modified
        " ●"
        " ○"
      )))
(defun render-mode-line-remote (remote)
  (if remote
      " @"
    ""))


;; mode-line section on left of screen
(setq mode-line-left-section
      (list
       ;; day and time
       ;; '(:eval (propertize (format-time-string " %b %d %H:%M ")
       ;;                     'face 'font-lock-builtin-face))

       ;; buffer status icon (dot)
       '(:eval (render-mode-line-status-icon buffer-read-only (buffer-modified-p)))
       ;; (render-mode-line-remote mode-line-remote)

       ;; the buffer name; the file name as a tool tip
       '(:eval (propertize " %b "
                           'help-echo (buffer-file-name)))

       ;; relative position, size of file
       ;; " ["
       ;; (propertize "%p" 'face 'font-lock-constant-face) ;; % above top
       ;; "/"
       ;; (propertize "%I" 'face 'font-lock-constant-face) ;; size
       ;; "] "
       ))

;; mode-line section on right of screen
(setq mode-line-right-section
      (list
       ;; git branch
       '(:eval (propertize (substring vc-mode 5)
                           'face 'font-lock-comment-face))

       ;; line and column
       " [" ;; '%02' to set to 2 chars at least; prevents flickering
       (propertize "%02l" 'face 'font-lock-comment-face) ":"
       (propertize "%02c" 'face 'font-lock-comment-face)
       "] "
       ;; (propertize org-mode-line-string 'face '(:foreground "#5DD8FF"))

       ;; the current major mode
       (propertize " %m" 'face 'font-lock-comment-face)
       " "
       ;; rich-minority minor modes
       rm--mode-line-construct
       "  "
       ))

(defun mode-line-render ()
  (append (append mode-line-left-section
                  (list
                   ;; function to right-justify part of modeline
                   ;; by filling center with spaces
                   '(:eval (s-repeat
                            (- (+ (window-total-width) 0)
                               (+
                                (length (format-mode-line mode-line-right-section))
                                (length (format-mode-line mode-line-left-section))))
                            " "))
                   )
                  mode-line-right-section)))


;; actually render the mode-line
;; (setq-default mode-line-format (mode-line-render))

;; move modeline to the top of the buffer
(setq-default header-line-format (mode-line-render))
;; (setq-default mode-line-format'(""))
;; hide empty mode-line
(setq-default mode-line-format nil)

;; reduce height of empty mode-line
(set-face-attribute 'mode-line nil :foreground "white" :background nil :box nil :overline "#1e212e")
(set-face-attribute 'mode-line-inactive nil :background nil :box nil :foreground "#232635" :overline "#1e212e")

(set-face-attribute 'vertical-border nil :background nil :foreground "#676E95")

;; decorate header-line
(set-face-attribute 'header-line nil
                    :background "#1c1f2b"
                    :foreground "#EEFFFF"
                    :box '(:line-width 5 :color "#1c1f2b")
                    :overline nil
                    :underline nil)
#+END_SRC

#+RESULTS:


* powerthesaurus in emacs

#+BEGIN_SRC emacs-lisp
(use-package powerthesaurus
  :straight t
  :config
  (bind-key* "s-p" 'powerthesaurus-lookup-word-dwim)
  )
#+END_SRC

#+RESULTS:
: t

* pim
#+BEGIN_SRC emacs-lisp
(defun maak-belachelijk ()
  (interactive)
  (let ((initial-end (region-end)))
  (if (use-region-p)
      (save-excursion
        (goto-char (region-beginning))
        (while (<= (point) initial-end)
          (message (format "%s"(point)))
          (goto-char (+
                      (+ (floor (* 3 (/ (abs (random)) (float most-positive-fixnum)))) 1)
                      (point)))
          (if (<= (point) initial-end)
                  (call-interactively 'upcase-char)))))))
#+END_SRC

#+RESULTS:
: maak-belachelijk
